# Importing relevant libraries

In [333]:
import pandas as pd
import numpy as np
import re

# Importing data

In [334]:
shark_attacks = pd.read_csv('C:/Users/pfaprado/Documents/IronHack/2021-01-22-project-shark-attack/attacks.csv', encoding='latin1')

# Preliminary analysis of data

In [335]:
# Let's show all the columns available through a max_columns = None and a head method.

pd.options.display.max_columns = None
shark_attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

## Size of the dataframe

In [336]:
# Let's check the number of elements in our dataframe.

shark_attacks.size

# We have about 617352 elements.

617352

## Shape of the dataframe

In [337]:
# Let's check the shape of our dataframe.

shark_attacks.shape

# We have 24723 entries of 24 types of data.

(25723, 24)

## Null-count and data types of the dataframe

In [338]:
# Let's check the non-null count and type of our data.

shark_attacks.info()

# Too many data entries without many infos such as Age, Time, Sex, Fatal, etc. Last columns can't be used.
# Year is a float64, should have been an integer.
# Age should have been specified as integer.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [339]:
# Specifically, about the types of data columns.

shark_attacks.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

## Columns of the dataframe

In [340]:
# Let's check all the columns availables. There are a bunch of columns with strange names at the end.

shark_attacks.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [341]:
# Let's check how many nulls we have in our dataset in each column.

null_cols = shark_attacks.isnull().sum()

null_cols

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

# Jaws Adventures: marketing shark feeding

In [342]:
"""
Our company, "Jaws Adventures", offers scuba diving for people.
We would like to analyse and market a new product: shark feeding.
However people may express distress to the idea of feeding sharks and the risks involved.
Let's analyse whether feeding sharks is safer than other activities already offered by our company.
"""

"""
For this, we will need to pull the data from columns:
- Activity (categorical)
- Fatal (Y/N) (categorical, binary: Y/N)

However, we know that the database is kind of messy, so we will need to do some data wrangling (cleaning) before.
"""

fatality_activity = shark_attacks[['Activity','Fatal (Y/N)']]

fatality_activity

          Activity Fatal (Y/N)
0         Paddling           N
1         Standing           N
2          Surfing           N
3          Surfing           N
4      Free diving           N
...            ...         ...
25718          NaN         NaN
25719          NaN         NaN
25720          NaN         NaN
25721          NaN         NaN
25722          NaN         NaN

[25723 rows x 2 columns]

In [343]:
# Let's count all the occurrences present in the column Fatal.

shark_attacks['Fatal (Y/N)'].value_counts()

# Highest portion of shark attacks are non-fatal.

N          4293
Y          1388
UNKNOWN      71
 N            7
y             1
2017          1
M             1
N             1
Name: Fatal (Y/N), dtype: int64

In [344]:
shark_attacks['Activity'].value_counts()

# Highest portion occurred during surfing, swimming or fishing (apparently).
# !However there are way too many categories to affirm anything at this point!

Surfing                                                                971
Swimming                                                               869
Fishing                                                                431
Spearfishing                                                           333
Bathing                                                                162
                                                                      ...
Collecting marine specimens                                              1
Harpooning turtles                                                       1
Standing on his hands                                                    1
Fishing from rocks, swept out to sea by large wave & treading water      1
Helmet diving in Miami Seaquarium                                        1
Name: Activity, Length: 1532, dtype: int64

In [345]:
# Let's understand the cases where the entries are null for Activity.

null_display_activity = shark_attacks[shark_attacks['Activity'].isnull() == True]
null_display_activity

# There is no apparent reason or correlation between null entries of Activity to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
47,2018.01.28,28-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,male,M,18,Injuries to right leg,N,08h00,Bull shark,"ABC.net.au, 01/28/2018",2018.01.28-ConeBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.28,2018.01.28,6256.0,NaN,NaN
108,2017.07.29.a,29-Jul-2017,2017.0,Unprovoked,USA,South Carolina,"DeBordieu Colony, Georgetown County",NaN,female x 2,F,12,Bite to left thigh / minor injury,N,Afternoon,NaN,"C. Creswell, GSAF",2017.07.29.a-Georgetown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.a,2017.07.29.a,6195.0,NaN,NaN
112,2017.07.23.b,23-Jul-2017,2017.0,Unprovoked,USA,New Jersey,Ventnor,NaN,Isabella Smith,F,NaN,Minor injury to hand,N,NaN,Sandtiger shark 2',A. Smith,2017.07.23.b-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.23.b,2017.07.23.b,6191.0,NaN,NaN
114,2017.07.22,22-Jul-2017,2017.0,Unprovoked,USA,Florida,"Snipes Point, Monroe County",NaN,female,F,40,Foot bitten,N,12h30,"""A small shark""","NBC Miami, 7/23/2017",2017.07.22-Keys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.22,2017.07.22,6189.0,NaN,NaN
154,2017.04.17.b,17-Apr-2017,2017.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,NaN,NaN,NaN,Minor bite to the foot,N,Afternoon,NaN,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [346]:
# Let's understand the cases where the entries are null for Fatal.

null_display_fatal = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display_fatal

# There is no apparent reason or correlation between null entries of Fatal to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [347]:
# Let's check for duplicates in our database and remove them:

before = len(shark_attacks)
shark_attacks = shark_attacks.drop_duplicates()
after = len(shark_attacks)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  19411

In [348]:
# That's how our database is now:

shark_attacks.head(7)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0,NaN,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN

## Data Cleaning: 'Fatal (Y/N)'

In [349]:
# Let's check the unique values of the column Fatal (Y/N) and its incidence in our database.

print(f"""
These are the occurrences of the values for Fatal (Y/N):
{shark_attacks['Fatal (Y/N)'].value_counts()}
""")

print(f"""
These are the unique values of the Fatal (Y/N) column:
{set(shark_attacks['Fatal (Y/N)'])}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.
""")

These are the occurrences of the values for Fatal (Y/N):
N          4293
Y          1388
UNKNOWN      71
 N            7
M             1
y             1
2017          1
N             1
Name: Fatal (Y/N), dtype: int64


These are the unique values of the Fatal (Y/N) column:
{nan, 'UNKNOWN', 'y', 'N', 'Y', 'M', ' N', '2017', 'N '}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.

### Checking uniques.

In [350]:
#Let's examine the case of 2017. There is only one entry classified as 2017.

case_2017_list = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == '2017']

case_2017_list

# As there is no information regarding the survivability on other columns,
# we will dismiss this entry in the dropping section.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
786,2012.06.10,10-Jun-2012,2012.0,Provoked,ITALY,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,57,Lower left leg injured PROVOKED ACCIDENT,2017,Morning,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0,NaN,NaN

In [351]:
# Let's examine the case of UNKNOWN. There are many entries classified as UNKNOWN.

case_UNKNOWN = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == 'UNKNOWN']
print(case_UNKNOWN)

# Printaremos também os índices referentes à entrada UNKNOWN. Futuramente retiraremos as linhas com base nessa lista.

case_UNKNOWN_list = list(case_UNKNOWN.index)
print(case_UNKNOWN_list)

# Examining the set of unique values of injury, we don't have any other relevant info on the fatality of the entries.
# So we can't take any action to classify these entries neither as Y nor as N.

set(case_UNKNOWN['Injury'])

# We will dismiss these entries since there is no info about fatality in the adjacent columns.

       Case Number           Date    Year        Type    Country  \
624     2013.09.08    08-Sep-2013  2013.0  Unprovoked        USA
1270  2008.04.20.a    20-Apr-2008  2008.0  Unprovoked  AUSTRALIA
2250    1997.06.07    07-Jun-1997  1997.0  Unprovoked     BRAZIL
2260    1997.02.21    21-Feb-1997  1997.0  Unprovoked        USA
2267    1996.12.29    29-Dec-1996  1996.0  Unprovoked  AUSTRALIA
...            ...            ...     ...         ...        ...
6167  1617.00.00.R  Reported 1617  1617.0  Unprovoked      INDIA
6169    1595.00.00           1595  1595.0  Unprovoked      INDIA
6171    1555.00.00           1555  1555.0  Unprovoked        NaN
6172    1554.00.00       Ca. 1554  1554.0  Unprovoked     FRANCE
6277       ND.0025    Before 1927     0.0  Unprovoked  AUSTRALIA

                   Area                            Location  \
624      South Carolina  St. Helena Island, Beaufort County
1270    New South Wales                       Crescent Head
2250     Rio de Janeiro          Copacabana, Rio de Janeiro
2260             Hawaii                 Sunset Beach, O'ahu
2267         Queensland                        Coolum Beach
...                 ...                                 ...
6167        West Bengal                        Ganges Delta
6169             Kerala                        River Cochin
6171                NaN                                 NaN
6172  Nice & Marseilles                                 NaN
6277    New South Wales      Spectacle Island, Port Jackson

                                               Activity  \
624                                                 NaN
1270                                                NaN
2250                                            Bathing
2260                                                NaN
2267                                            Surfing
...                                                 ...
6167                                                NaN
6169  Ship lay at anchor & man was working on its ru...
6171                                           Swimming
6172                                                NaN
6277                                                NaN

                               Name Sex   Age  \
624                          female    F  NaN
1270                Jamie Adlington    M  NaN
2250              José Luiz Lipiani    M  NaN
2260                Gersome Perreno    M  NaN
2267                     Blair Hall    M   18
...                             ...  ...  ...
6167                  Indian people  NaN  NaN
6169                           male    M  NaN
6171                           male    M  NaN
6172          males (wearing armor)    M  NaN
6277  male, the Sergeant of Marines    M  NaN

                                                 Injury Fatal (Y/N)   Time  \
624                                          No details     UNKNOWN    NaN
1270                                                NaN     UNKNOWN    NaN
2250                                                NaN     UNKNOWN    NaN
2260                                         No details     UNKNOWN    NaN
2267                                                NaN     UNKNOWN  18h00
...                                                 ...         ...    ...
6167                                                NaN     UNKNOWN    NaN
6169  Leg severed mid-thigh, hand severed, arm above...     UNKNOWN    NaN
6171                                                NaN     UNKNOWN    NaN
6172                                                NaN     UNKNOWN    NaN
6277                                                NaN     UNKNOWN    NaN

                   Species                      Investigator or Source  \
624                     NaN                           WIS-TV, 9/9/2013
1270     Tiger shark, 2.3m                              T. Peake, GSAF
2250                    NaN                            Globo, 6/9/1997
2260                    NaN                                  G. Balazs
2267                    NaN            The Advertiser, 12/30/1996, p.3
...                     ...                                        ...
6167                    NaN    H. Edwards, p.31, citing Samuel Purchas
6169                    NaN  The Voyage of John Huyghen van Linschoten
6171                    NaN                               Olaus Magnus
6172  Possibly white sharks                               G. Rondelet
6277                    NaN                                  H. Capper

                                  pdf  \
624          2013.09.08-St-Helena.pdf
1270       2008.04.20.a-Adlington.pdf
2250        1997.06.07-NV-Lipiani.pdf
2260        1997.02.21-NV-Perreno.pdf
2267         1996.12.29-BlairHall.pdf
...                               ...
6167           1617.00.00-Purchas.pdf
6169            1595.00.00-Cochin.pdf
6171    1555.00.00 - Olaus Magnus.pdf
6172          1554.00.00-Rondelet.pdf
6277  ND-0025-Sgt-SpectacleIsland.pdf

                                           href formula  \
624   http://sharkattackfile.net/spreadsheets/pdf_di...
1270  http://sharkattackfile.net/spreadsheets/pdf_di...
2250  http://sharkattackfile.net/spreadsheets/pdf_di...
2260  http://sharkattackfile.net/spreadsheets/pdf_di...
2267  http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                 ...
6167  http://sharkattackfile.net/spreadsheets/pdf_di...
6169  http://sharkattackfile.net/spreadsheets/pdf_di...
6171  http://sharkattackfile.net/spreadsheets/pdf_di...
6172  http://sharkattackfile.net/spreadsheets/pdf_di...
6277  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number.1  \
624   http://sharkattackfile.net/spreadsheets/pdf_di...    2013.09.08
1270  http://sharkattackfile.net/spreadsheets/pdf_di...  2008.04.20.a
2250  http://sharkattackfile.net/spreadsheets/pdf_di...    1997.06.07
2260  http://sharkattackfile.net/spreadsheets/pdf_di...    1997.02.21
2267  http://sharkattackfile.net/spreadsheets/pdf_di...    1996.12.29
...                                                 ...           ...
6167  http://sharkattackfile.net/spreadsheets/pdf_di...  1617.00.00.R
6169  http://sharkattackfile.net/spreadsheets/pdf_di...    1595.00.00
6171  http://sharkattackfile.net/spreadsheets/pdf_di...    1555.00.00
6172  http://sharkattackfile.net/spreadsheets/pdf_di...    1554.00.00
6277  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0025

     Case Number.2  original order Unnamed: 22 Unnamed: 23
624     2013.09.08          5679.0         NaN         NaN
1270  2008.04.20.a          5033.0         NaN         NaN
2250    1997.06.07          4053.0         NaN         NaN
2260    1997.02.21          4043.0         NaN         NaN
2267    1996.12.29          4036.0         NaN         NaN
...            ...             ...         ...         ...
6167  1617.00.00.R           136.0         NaN         NaN
6169    1595.00.00           134.0         NaN         NaN
6171    1555.00.00           132.0         NaN         NaN
6172    1554.00.00           131.0         NaN         NaN
6277       ND.0025            26.0         NaN         NaN

[71 rows x 24 columns]
[624, 1270, 2250, 2260, 2267, 2295, 2307, 2323, 2328, 2388, 2404, 2409, 2648, 2650, 2661, 2806, 2882, 2900, 2943, 2996, 2998, 3006, 3038, 3041, 3298, 3396, 3411, 3429, 3434, 3507, 3545, 3552, 3712, 3774, 3794, 3838, 3841, 4060, 4208, 4256, 4269, 4310, 4323, 4517, 4689, 4786, 4787, 4976, 4998, 5029, 5159, 5270, 5347, 5409, 5555, 5615, 5653, 5656, 5674, 5708, 5709, 5998, 6081, 6153, 6165, 6166, 6167, 6169, 6171, 6172, 6277]

{'"Painfully injured" but no details',
 'Calf removed, not known if he survived ',
 'Details unknown, possibly a PROVOKED INCIDENT',
 'Involved a speared shark but no other details PROVOKED INCIDENT',
 'Leg severed mid-thigh, hand severed, arm above elbow and part of buttocks. Not known if he survived',
 'Man landed at Cape Levêque lighthouse in critical condition after being bitten by a shark. Not known if he survived.',
 'No details',
 'No details, "recovering in Darwin Hospital"',
 'No details, it was the year the first settlers came ashore in Holdfast Bay, Port Pirie',
 'No details, listed as PROVOKED INCIDENT',
 'No injury',
 'Severe bite to thigh. Not known if he survived',
 'Shark involvement not confirmed',
 'Unprovoked, but circumstances unknown',
 nan}

In [352]:
# Let's examine the case of M. There is only one entry classified as M.

case_M = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == 'M']
print(case_M)

# Printaremos também os índices referentes à entrada M. Futuramente retiraremos as linhas com base nessa lista.

case_M_list = list(case_M.index)
print(case_M_list)

# It seems it was only a laceration and the input was supposed to be N, not M. We will change it to 'N' (not fatal).

      Case Number         Date    Year      Type           Country      Area  \
285  2016.04.18.b  18-Apr-2016  2016.0  Provoked  FRENCH POLYNESIA  Tuamotos

         Location      Activity         Name Sex  Age  \
285  Makemo Atoll  Spearfishing  Hoata Iotua    M  22

                                                Injury Fatal (Y/N)     Time  \
285  Laceration to knee by speared shark PROVOKED I...           M  Morning

                 Species  Investigator or Source                     pdf  \
285  Grey reef shark, 2 m   TNTV News, 4/19/2016  2016.04.18.b-Iotua.pdf

                                          href formula  \
285  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                  href Case Number.1  \
285  http://sharkattackfile.net/spreadsheets/pdf_di...  2016.04.18.b

    Case Number.2  original order Unnamed: 22 Unnamed: 23
285  2016.04.18.b          6018.0         NaN         NaN
[285]

In [353]:
# Showing all NaN in column Fatal (Y/N)

null_display_fatal = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display_fatal

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0,NaN,NaN
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0,NaN,NaN
6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [354]:
# Let's examine the case of NaN. There are many entries like this.
# We will reclassify the values of NaN based on columns 'Injury' and 'Species' since it seems the data entrier
# had put some keywords such as FATAL and Death on these columns and could lead us to improve our dataset.

# Let's define a function to apply to our dataset, where we classify the values in Fatal_adjusted based on
# columns 'Injury' and 'Species', when they do have the info 'death' or 'fatal'.

# WARNING: column Species is written with a space at the end = 'Species '

def fatal_classifier(row):
    
    """
    Essa função classificará em N ou Y com base nas strings ou lista de strings encontradas
    nas colunas Injury e Species.
    """
    
    if row['Fatal (Y/N)'] == ('Y' or 'y'):
        return 'Y'
    
    elif row['Fatal (Y/N)'] == ('N' or 'n'):
        return 'N'
        
    elif pd.isnull(row['Fatal (Y/N)']) == True: 
        
        try:            
            Injury_match_list = re.findall('[fFdD][aAeE][tTaA][aAtT][lLhH]', row['Injury'])    #variações de 'death' e 'fatal'
            Species_match_list = re.findall('[fFdD][aAeE][tTaA][aAtT][lLhH]', row['Species '])    #variações de 'death' e 'fatal'
            
            if  len(Injury_match_list + Species_match_list) == 0:
                return 'N'
    
            else:
                return 'Y'
        
        except:
            return 'Non available'
        
        
    else:
        return row['Fatal (Y/N)']

    
shark_attacks['Fatal_adjusted'] = shark_attacks.apply(fatal_classifier, axis=1)


#print(shark_attacks['Fatal_adjusted'] == shark_attacks['Fatal (Y/N)'])

null_display_fatal = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display_fatal

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN,Non available
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN,Y
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN,N
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN,Non available
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0,NaN,NaN,Non available
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0,NaN,NaN,Non available
6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non available
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non available
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non available

### Row dropping

In [355]:
# Let's drop the rows where Fatal_adjusted is Non available, through a list of indexes.

list_to_be_dropped = shark_attacks.loc[shark_attacks['Fatal_adjusted'] == 'Non available'].index

# Dropping the list of indexes
shark_attacks_v1 = shark_attacks.drop(index=list_to_be_dropped)

In [356]:
# Let's drop the case of 2017 (row 786).
case_2017_list = [786]

In [357]:
# Let's drop the case of UNKNOWNs ().
    # case_UNKNOWN_list
    
shark_attacks_v2 = shark_attacks_v1.drop(index=case_UNKNOWN_list)
shark_attacks_v3 = shark_attacks_v2.drop(index=case_2017_list)

### Row adjusting

In [358]:
# For M, we will update the row 285 for Fatal (Y/N) from M to N.

shark_attacks_v3.loc[285,'Fatal_adjusted'] = 'N'

# Checking the value update:

print(shark_attacks_v3.loc[285,'Fatal_adjusted'])

N

### Stripping spaces in Fatal_adjusted

In [359]:
def strip_spaces(x):
    return x.strip()    

shark_attacks_v3['Fatal_adjusted'] = shark_attacks_v3['Fatal_adjusted'].apply(strip_spaces)

In [360]:
set(shark_attacks_v3['Fatal_adjusted'])

{'N', 'Y', 'y'}

### Upper case all strings in Fatal_adjusted

In [361]:
shark_attacks_v3['Fatal_adjusted'] = shark_attacks_v3['Fatal_adjusted'].str.upper()

In [362]:
set(shark_attacks_v3['Fatal_adjusted'])

# We obtained a set containing only 'N' and 'Y' at the end.

{'N', 'Y'}

In [363]:
# The database updated:

shark_attacks_v3['Fatal_adjusted'].value_counts()

N    4580
Y    1620
Name: Fatal_adjusted, dtype: int64

### Total death rate (result)

In [364]:
death_rate = 1620/4580
print(f"""The total death rate for the time span was {death_rate*100}%. 
This number could be lower but hardly higher, since we dropped the columns where no conclusion could be drawn
and they were mostly about lacerations and such.""")

The total death rate for the time span was 35.37117903930131%.
This number could be lower but hardly higher, since we dropped the columns where no conclusion could be drawn
and they were mostly about lacerations and such.

In [365]:
shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y

## Data Cleaning: 'Activity'

### Checking uniques.

In [366]:
# Let's check the unique values of the column Activity.

print(set(shark_attacks['Activity']))

# Problematic: anedoctal(too many descriptions).
# We will have to categorize them better, maybe through bins.

{nan, 'Surfing (lying prone on his board)', 'Free diving, hunting crayfish', 'Japanese freighter Bokuyo Maru burned & sank', 'Catching a turtle', 'Fisherman', 'Scuba diving (but on surface)', 'Swimming from makeshift raft  to life vest after fishing boat sank', 'Fishing, attempted to take a netted shark', 'Paddling on surfboard', 'Attempting to fix motor', 'Free diving / spearfishing, from paddleboard & floating on the surface', 'Beach seine netting', "Accidentally stood on hooked shark's tail before attempting to gut it ", 'Ocean racing', 'Cage Diving', 'Free diving but treading water at surface', 'Swimming, towing a kayak', 'Diving for pearls', 'Scuba diving (ascending using scooter)', 'Aircraft exploded', 'Fishing for yellowtail', 'Bathing alongside US Naval ship', 'Washing cooking pans', 'Sea Disaster, sinking of the fishing  launch Mavis', 'Canoeing', 'Paddle-skiing', 'Swimming near jetty', 'Windsurfing', 'The troopship Britannia was sunk by the German raider Thor', 'Dragging banana seeds through the shallows', 'Sitting in shallows', 'Swimming / shipwreck', 'Sight-seeing', 'Night Surfing', 'Surfing (or body boarding)', 'Known as The Battle of the Bismarck Sea :  8 Japanese destroyers guarding a convoy of 8 transports were attacked by 129 Allied fighters, 207 bombers & 3 squadrons of the Royal Australian Air Force. ', 'Kite Boarding', 'Rowing ', 'Floating on air mattress', 'Spearfishing / Scuba diving (at surface)', 'Fell overboard while fishing for sharks', 'Swimming ashore from a "filibuster"', 'Murdered', 'Walking in chest-deep water', "Sitting in bow of her father's 5 m boat", 'Sitting on surfboard', 'Washing sand off a speared fish', 'Hunting crayfish ', 'S.S. Marine Sulphur Queen, laden with molten sulphur was bound from Beaumont, Texas for Norfolk, VA, when she disappeared with 39 on board', 'Sea Disaster Sinking of ferryboat Christina', "Fishing from 34' boat when pulled overboard by hooked shark", 'Body Boarding', 'Spearfishing with Joe Turner (24). Shark attracted to speared halibut on belt of one diver, tried to bite Ide\x92s speargun & he shot it in the mouth', 'Wading & pushing dinghy toward  the shallows', 'Boogie boarding', 'Spearfishing / freediving', 'Bathing with sister', 'Jumped off surfboard & landed on the shark', 'Spearfishing & diving for paua', 'Feeding sharks', 'Sinking of the ferryboat Bongbong 1', 'Boat capsized', 'Shipwrecked; adrift on raft for 2 days & 2 nights', "Fell off surfboard 20' from shore", 'Free diving, carrying speargun', 'Sailing from Gingood, Misamis Oriental to Sagay (normally a 2-day voyage) capsized with 6 on board, three men were taken by sharks when they attempted to swim to shore.', 'On expedition filming a feature movie & standing on tripod', 'Diving for coins thrown from ship S.S. Moeraki', 'Knocked into the water', 'Snorkeling on surface', 'Floating in inner tube', 'Surfing on "chest board" (boogie board?)', "Standing on landed shark's tail", 'Escaping from Alacatraz', 'Body boarding', 'Attempting to attract dolphins', 'Free diving for sinkers', 'Swimming close to wharf', 'Floating', 'Collecting fish in military trap when bitten by captured shark that had been shot by soldiers with Garten', 'Fishing for sharks when he became entangled in net & fell overboard', 'Hunting turtle', 'Playing on a sandbar', 'Paddling on surfboard or body board', 'Fishing for snapper', 'Jerked overboard while pole fishing for tuna', 'Dived from dinghy to retrieve oar in heavy seas', 'Rescuing seaman after ship sunk by German raider', 'Attacked shark with fists', 'Swimming after their boat capsized', 'Removing fish from a trap', 'Dived naked into the water on a bet', 'Standing / Snorkeling', 'Fishing, two large sharks passed. He speared one and it bit him', 'Jumped overboard from Norwegian steamship Venator', 'Spearfishing (free diving)', 'Standing / Bathing', 'Fishing in waist-deep water', 'Fishing for cod', 'boat from City of Naples capsized', 'Japanese POW ship Arisan Maru with 1800 American prisoners of war on board bound for slave labor camps was torpedoed by an American submarine', 'Fell overboard & swimming', 'Free diving with goggles', 'After rowing skiff was holed by shark, he was attempting to swim ashore', 'Fishing boat swamped in a storm', 'Fishing on a boat', 'Rowing an inflatable dinghy', 'Swimming / escaping imprisonment ', 'Marathon swimming', 'Spearfishing, carrying fish on belt', 'Swimming after boat became disabled', 'Bathing in knee-deep water', 'Fishing for the shark that killed George Lundberg', 'Feeling the shark\x92s teeth', 'Parachuted from balloon', 'Catching sardines', 'Diving for Abalone', 'B-24 aircraft crashed  into the sea', 'Ran into the water', 'Splashing / wading', 'Helmet diving', 'Fishing (illegally)', 'Survived crash of two-engine  C-46 transport plane carrying 62 migrant workers from Puerto Rico to USA ', 'The Dwarka foundered', 'Bathing close inshore', 'Spearfishing using Scuba', 'American minesweeper USS YMS-472 foundered in a typhoon - swimming to shore', 'Sea Disaster : Wreck of the Carrie E. Long', 'Free diving & spearfishing', 'Spearfishing, pulled shark\x92s tail', 'Fishing for white shark', 'Sinking of the cargo ship Mark Jason', 'Sleeping in anchored boat', 'Free diving for abalone from Zodiac (submerged)', 'Carrying a supposedly dead shark by its mouth', 'Fishing, probably with a net', 'Free diving Spearfishing', 'Sea disaster, wreck of the Alfred Watts', 'Swimming at side of small boat', 'Disappeared 11 days earlier, probable homicide victim', 'Spearfishing, hunting crayfish', 'Skin diving for trepang but at surface next to the boat', 'Swimming with boogie board', 'Paddling in knee-deep water', 'Taking boat from California to Florida when it ran aground & he was swimming back to boat', 'Scuba diving & feeding fish', 'Shark fishing on the Don Agustín-VI. ', 'Treading water/ Surfing', 'Washed into sea while picking opihi & attacked by 2 large sharks ', 'Floating with life buoy after pilot launch capsized', 'Standing alongside surfboard', 'Fishing for rock lobster', 'The coastwise steamer San Basilio capsized in a typhoon', 'Spearfishing/ filming', 'ship torpedoed 400 miles off the African coas. Man was clinging to hatch cover', 'Crossing the river mouth', 'Checking fish traps, fell into the water', 'Swimming', 'Swimming on surface', 'Scuba diving in aquarium tank', 'Spearfishing, Scuba diving', "Swimming at surface through school of feeding 2.5' to 5\x92 sharks", 'Diving for pen shells', 'Tzenny Chandris, a Greek freighter laden with scrap iron, foundered in heavy weather', 'Free diving for molluscs', 'Floating ', 'Scuba Diving', 'Traveling by boat', 'Wading, fishing for flounder', 'The Pacquebot Laconia, enroute to Liverpool with 600 Italian prisoners onboard, was torpedoed by the German submarine  U-156 and only 2 rafts were launched before the ship went down. Unable to board an overcrowded raft, he was swimming.', 'Lobster diving using Scuba', 'Escaping from blackbirding vessel', 'Fishing / cleaning fish, dived into water to retrieve a lost fish', 'Surfing / treading water', 'Swimming after his canoe capsized', 'Sea disaster, foundering of the cargo vessle M/V Dorolonda', 'Fishing for albacore', 'Floating, holding onto an oar after dory capsized', 'His balloon crashed in the harbor', 'Floating in tube', 'Diving / fishing', 'Wading?', 'Jumped overboard from torpedoed Panamanian freighter', 'Boat capsized?', 'Pulling shark from the water', 'Fishing (trolling)  from canoe', 'Fell into water while attempting to boat a swordfish', 'Aircaft exploded', 'Swimming in section of river used for washing clothes & cooking utensils', 'Spearfishing with Scuba gear', 'Sponge diving', 'Scuba diving & spearfishing ', 'Collecting fish by lamplight in gully', 'A dhow capsized', 'Dragging stranded shark ashore', 'Spearfishing on Scuba', 'The cutter Francis Adams foundered', 'Towing rubber dinghy', "63' fishing boat Sno' Bay foundered", 'The 426-ton cargo ship Mia, laden with cement, capsized in heavy seas ', 'canoeing', '90 European civilians, many women & children, were placed on the deck of a Japanese submarine that submerged when it was well offshore', 'Scuba diving (submerged riding a scooter)', 'Attempting to chase shark out to sea', 'Copra vessel with 19 on board was wrecked in a squall', 'Dragging stranded shark into deeper water', 'Swimming to shore from the Medic', 'Adrift on life raft', 'Colombian  (Avianca) DC-4 airliner plunged into the sea 5 minutes after takeoff', 'Schooner sank during a storm', "Fishing, removing gaff from shark's mouth", 'Surfing / Swimming', 'Wading, when he stepped on the shark', 'Paddling a canoe', 'Motor boat Rebel Belle lost', 'Taken as he dived into the water', 'Sailboarding, fell into water 100 yards outside the breakwater', 'Spearfishing & holding catch', 'Net-fishing', 'Being pulled to shore from wreck of 25-ton fishing vessel Alan S', 'Skindiving for specimens', 'Lying in 2 feet of water', 'Diving, but on the surface when bitten by the shark', 'Tuna fishing, standing on stern platform that was submerged by waves', 'Free diving or wading back to shore', 'Small boat swamped, 4  people swimming to shore but he fell behind the other 3 and vanished', 'Standing in inner tube', 'Fishing for tunny', 'Trailing hand in the water', "Fishing from 32' boat", 'Free diving, collecting shells', 'Fishing, Struck by another shark when removing shark from line', 'Fishing from surfski', 'Dynamiting fish', 'Surf skiing', 'Swimming from capsized pirogue', 'Fell off banana boat', 'Body surfing, stood up on sandbar', 'Sitting in the water', 'Killing  sharks', 'Jet skiing', 'Washed off catamaran in the surf', 'Spearfishing & had just speared a ulua', 'Sculling', 'Free diving ', 'Canoe capsized by shark', 'Helping angler land a shark', 'Bathing in river', 'Washing a dog', 'Murder', 'Free diving with a pod of dolphins', 'Jumped overboard to rescue companion', 'Chasing shark out of bathing area while riding on a surf-ski', 'Wreck of the Storm King', 'Swimming alongside the schooner Catherine Wilcox', 'Free diving for trochus shell, swimming to dinghy', 'Attempting to catch a crocodile', 'The steamer Tahiti collided with the ferry Greycliffe', 'Surfing, but treading water', 'The 168-ton Belmore foundered in heavy seas', 'Bathing/Swimming', 'Moving a shark in a net ', 'Snorkeling, carrying a speared fish in her hand', 'When  a deckhand  jumped overboard, McIver dived after him with a rescue line.', "Bathing in 5' of water", "Sitting in 3' of water", 'Spearfishing, but swimming at surface', 'Playing on rock, slipped & fell into the water', 'Yacht of Michael Howell capsized', 'Bathing / standing', 'Stamding', 'Put foot inside mouth of supposedly dead shark', 'Attempting to rescue woman seized by shark', 'Air Disaster - Piper aircraft crashed into the sea, killing all on board', 'Jumping in the waves', 'Fishing from rocks, swept out to sea by large wave & treading water', 'Harpooning turtles', 'Collecting marine specimens', 'Leicester abandoned in a hurricane', 'Ferry boat Dona Paz with 4431 passengers exploded & caught fire when she collided with an  oil tanker ', 'Surf fishing', 'Attempting to rescue drowning man', 'Playing volleyball with friends', 'Swimming a quarter mile offshore', 'Swimming, after falling overboard', 'Attempting to illegally enter the USA', 'Removing hook from shark', 'Painting a ship', 'Flying Fortress bomber aircraft went down after daytime raid on Naples. He was swimming on the surface', 'Freediving for trochus shell (submerged)', 'Angling', 'Washed overboard by swell', 'Swimming to canoe', 'Wading with surfboard', 'Body surfing / treading water', 'Fishing for shrimp', 'Swimming with speared fish', 'Fell overboard  from the Taiwanese fishing trawler Lien Cheng Feu ', 'Batin', 'Spearfishing, shot shark, hauled it onto boat', 'Diving in tuna net', 'Diving', 'Hauling in net with shark in it', 'Oystering', 'Washing clothes on stairs', 'Fishing boat with 4 men on board was rammed & capsized by  a shark, throwing all occupants into the water', 'Pearl diving, but standing in the water', 'Fell overboard from the steamship Chala', 'Boat capsized, swimming to shore', 'Fishing from paddleski', 'Scurfing (surfboard being  towed behind a boat)', 'Fishing for white sharks', 'Paddling outrigger canoe', 'Diving for pearl shell', 'ship William Penn grounded & broke apart', 'Abandoning burning steamship Don Juan', 'Fishing, when line became snagged on rock & he dived into water to free it ', 'Jumped overboard', 'Free diving, surveying a pipeline & examing cathodes under jetty', 'Small vessel with 13 men on board capsized crossing the bar and 6 men drowned.  The 7 survivors were swimming to shore', 'Floating or standing', 'Taking wife to beach & about 1 m from the shore', 'In boat being towed by ship, Karnak', 'Sea Disaster', '17 Maldivians adrift in open boat for 31 days', 'Fishing with dynamite, afterwards in water retrieving catch', 'Fishing, had just speared a ulua', 'Unknown, their unoccupied yawlboat was recovered', 'Returning to shore, collided with shark', 'Climbing back on ship', 'Gaffing netted shark', 'Fishing for rock lobsters', 'Kayaking or Wave skiing', 'Adrift after ditching plane in the sea', 'Fell overboard?', 'Spearfishing, had fish on his spear', 'Swimming, poaching perlemoen', 'Shark tagging', 'Body found floating next to his ship', 'Surfing, lying on surfboard', 'Killing a shark', 'Chumming for white sharks', 'Floating with life preserver after his boat foundered', 'Spear fishing', 'SCUBA Diving', 'Fishing for snappers & cleaning mullet. Put mullet over side of boat to wash it', 'Fishing for blue sharks', 'Floating on an inflatable raft', 'The Christie V sank on 11/6/1988, survivors were adrift on a dinghy', 'Swimming beside launch', 'Japanese aircraft shot down. He was one of two survivors rescued by the U.S. destroyer Mugford', 'Pulling raft out to ride to shore', 'Standing, washing rear wheels of his ambulance in ankle-deep water', 'Boogie boarding or Surfing', 'Swimming after falling overboard from the sealing ship Vesper', 'Washing his feet', 'Snorkeling \x96 hunting crayfish and abalone', 'Free diving, Spearfishing', 'Surfing, paddling shorewards', 'Diving from lugger', 'Fishing from market fishboat Sea Spray', 'Bathing in waist-deep water', 'Playing soccer in the water', 'Swimming to shore from boat or kayak', 'Clinging to overturned rowing boat', 'Swimming, towing an empty barrel', 'The USS Wahoo torpedoes & sank the Japanese troop transport Buyo Maru', 'Fishing (Seining)', ' a canoe was pursuing a schooner that had forcibily abducted 5 young girls', 'Bathing alongside ship', "Adrift on a 4'  raft for 32 days", 'Body surfing?', 'Jumped overboard to rescue a man', 'Treading water while alongside capsized yacht', 'Salvaging a shipwreck', 'In rubber dinghy with Captain Eddie Rickenbacker for 21 days. ', 'Swimming, after single-engine aircraft went down in the sea', 'Inebriated, woke from sleep and fell off deck into the water ', 'Attempting to swim across the Atlantic Ocean', 'Loss of the schooner Nomad', 'Petting a shark', "Zosimo & his son, Jeffrey Popa, failed to return from overnight fishing trip in a 14' boat, Boat apparently sank, debris recovered but his son & boat were never found", 'Pearl diving from lugger', ' ', 'Dragging a shark', 'Paddling', 'Chumming for sharks', 'Fell onto dead shark', 'Shark fishing', 'Scuba Diving for lobster (at surface)', 'Wading, netting fish', 'Fishing, trying to catch the end of his fishing line', 'boat from the Austrian ship Elizabeth', 'Hookah diving for sea urchins', 'Fishing from shore, washed into the sea', 'Net fishing, fell into the water', "Scientific research (Dr. Sonny Gruber's student)", 'Sinking of the M/V Mindoro during a typhoon', 'Windsurfing (urinating on his board)', 'Attempting to drive shark away from the beach', 'Fishing, boat capsized', 'Conch diver', 'Swept out to sea while fishing', 'Diving off wharf', 'On fishing boat & trailing hand in the water', 'yachtsman in a zodiac', 'Closed circuit diving (submerged). Diving to recover jettisoned packets of opium for police', 'Standing on ship deck', 'Spearfishing ', 'During "an exhibition" he was tied in sack & thrown overboard ', 'Teasing a shark', 'Playing / standing', 'Steinhart Aquarium', "Lying prone in 2' of water", 'Bathing in 2 feet of water', 'Scuba diving & spearfishing', 'Accidentally dragged overboard from the sampan Holokahana into school of yellowfin tuna', 'Royal Hawaiian skymaster DC-6B aircraft went down with  58 passenger & crew', 'On a "shark hunt"', 'Hookah diving for abalone', 'Hookah diving (submerged)', 'Freedom Swimming', 'Dismantling cable buoys of the cable ship All America', 'Wooden fishing boat', 'Attempted to return injured shark to the sea', 'Speared a grouper, saw shark but it came for him instead of the fish so he fired spear into shark\x92s mouth. Then shark took grouper but unable to swallow because of the spear in its mouth.', 'Fell overboard from sponge vessel', 'Reviving a sedated shark', 'Pulling anchor', 'The cutter yacht Cutty Sark sank', 'Helping friend land hooked shark', 'Spearing a shark', 'Vessel capsized, wading ashore carrying an oar', 'Attempting to free the shark', 'boat with 46 people on board capsized', 'yachting accident', 'Cleaning a tank', 'A barque wrecked', 'Fishing for tuna', 'Competing in the Woodvale Atlantic Rowing Race', '25-foot cabin cruiser Happy Jack sank in heavy seas', '3 men & 2 boys picked up wearing life jackets and with inner tube', 'Diving for trochus', 'Swept overboard', 'Paddle Boarding', 'Washed overboard into school of fish', 'H.M.S. Cornwall & H.M.S.Dorsetshire sunk by Japanese dive bombers. Officers & men in the water formed a circle with 60 of their dead in the center for 36 hours', 'Swimming with mask & snorkel', 'Swimming near canoe', 'Swimming 3 miles offshore', 'Fishing from launch, fell into net with shark', 'British ship, Britannia,  was loading lumber. He was bathing', 'Fell from wharf into water & attacked immediately', 'Fishing for bottom fish', 'Free diving (but on surface)', 'Standing on sandbank', 'Swimming with board', 'The passenger ship Pioneer Cebu  capsized & sank in Typhoon Irma', 'Fishing for bluefish', 'Fishing, hauling in a set line', 'Shipwrecked', 'Investigating shark sighting', "Diving to untangle a crab trap line from boat's propeller", 'Bather', 'Rescuing', 'Bitten while cutting shark from net', 'Free diving for abalone (ascending)', 'Wading, knocked down & swept away by large waves', 'Splashing ', 'Kayak fishing for sharks', 'Resting on surfboard', 'Scuba diving, attempting to catch a captive shark', 'Sea disaster, wreck of the sloop Sara', 'Swimming at edge of channel', 'Wading or swimming', 'Cleaning fish', 'Hunting seals', 'Crabbing (spearing crabs)', 'Diving from dinghy for trochus shell', 'Diving. Shark \x93swallowed\x92 his hand, so he threw his other around the shark and went \x93shark-back riding\x94 for 30 yards until the shark opened its jaws', 'boat capsized during filming', 'Anti-sabotage night dive exercise alongside destroyer (Scuba diving)', 'Skindiving', 'Scuba diving ', 'Diving?', 'Walking, carrying surfboard & stepped on shark', 'Body surfing', 'Vessel caught fire & capsized, survivors in the water', 'Net fishing', 'Freedom swimming', 'Swimming in canal', 'Hardhat diving ', "40' fishing boat sank", "Days before the surrender of Singapore, the 3 men escaped to Sumatra where they acquired a 17' dinghy. After 125 days at sea they drifted back to Sumatra", 'Spearfishing, carrying his catch', '"Swimming vigorously"', 'Removing shark from net ', 'Fell overboard from the Selim', 'cargo ship Southern Isle sank at 04h00', 'The World Liberty and the tanker Mosli collided. The  Halcyon Breeze sent a lifeboat to the rescue, but it was smashed, throwing 6 men in the  water.', 'Launching rowboat through the surf', 'Skin diving ', 'boat from ship Josephine capsized in squall', 'Boat stopped to repair e

In [369]:
print(f"""

We will base this on the following sources:

https://en.wikipedia.org/wiki/List_of_water_sports
https://www.themost10.com/popular-water-sports/

- Fishing: Fishing / Spearfishing / Deep sea fishing / Big game fishing
- Diving: Diving / Scuba Diving / Snorkeling / Freediving
- Surfing: Surfing
- Swimming: Swimming
- Parasailing: Parasailing
- Boats: Kayaking / Canoeing / Rafting / Boating
- Skiing: Jet Skiing / Water Skiing
- Wake: Wakeboarding / Wakesurfing
- Kite: Kitesurfing / Kiteboarding
- Motorized boats: Yachting / Ship
- Other activities

...and finally...

- Shark feeding

""")

We will base this on the following sources:

https://en.wikipedia.org/wiki/List_of_water_sports
https://www.themost10.com/popular-water-sports/

- Fishing: Fishing / Spearfishing / Deep sea fishing / Big game fishing
- Diving: Diving / Scuba Diving / Snorkeling / Freediving
- Surfing: Surfing
- Swimming: Swimming
- Parasailing: Parasailing
- Boats: Kayaking / Canoeing / Rafting / Boating
- Skiing: Jet Skiing / Water Skiing
- Wake: Wakeboarding / Wakesurfing
- Kite: Kitesurfing / Kiteboarding
- Motorized boats: Yachting / Ship
- Other activities

...and finally...

- Shark feeding

### Classifying

In [370]:
shark_attacks['Activity'] = shark_attacks['Activity'].astype(str)

def activity_classifier(row):
    """
    This function will classify the rows present in columns 'Activity' based on a list of strings set before.  
    """
    
    feeding_match_list = re.findall('[fF][eE][eE[dD]\w*', row['Activity'])
    fishing_match_list = re.findall('[fF][iI][sS][hH][iI]\w*', row['Activity'])
    diving_match_list = re.findall('[dD][iI][vV]\w*', row['Activity'])
    surfing_match_list = re.findall('[sS][uU][rR][fF]\w*', row['Activity'])
    swimming_match_list = re.findall('[sS][wW][iI][mM]\w*', row['Activity'])
    parasailing_match_list = re.findall('[pP][aA][rR][aA][sS][aA][iI][lL]\w*', row['Activity'])
    skiing_match_list = re.findall('[sS][kK][iI]\w*', row['Activity'])
    wake_match_list = re.findall('[wW][aA][kK][eE]\w*', row['Activity'])
    kite_match_list = re.findall('[kK][iI][tT][eE]\w*', row['Activity'])
    boating_match_list = re.findall('[kKcCrRbB][aAoO][yYnNfFaA][aAoOtT][eE]?\w*', row['Activity'])
    motorized_match_list = re.findall('[yYsS][aAhH][tTiI][cCpP][hH]?\w*', row['Activity'])
    
    if  len(feeding_match_list) != 0:
        return feeding_match_list[0]
    
    elif len(fishing_match_list) != 0:
        return fishing_match_list[0]
    
    elif  len(diving_match_list) != 0:
        return diving_match_list[0]
        
    elif len(surfing_match_list) != 0:
        return surfing_match_list[0]
        
    elif len(swimming_match_list) != 0:
        return swimming_match_list[0]
    
    elif len(parasailing_match_list) != 0:
        return parasailing_match_list[0]
    
    elif len(skiing_match_list) != 0:
        return skiing_match_list[0]
    
    elif len(wake_match_list) !=0:
        return wake_match_list[0]
    
    elif len(kite_match_list) !=0:
        return kite_match_list[0]
    
    elif len(boating_match_list) != 0:
        return boating_match_list[0]
    
    elif len(motorized_match_list) != 0:
        return motorized_match_list[0]
    
    else:
        return 'Others'
    
    
shark_attacks_v3['Activity_adjusted'] = shark_attacks.apply(activity_classifier, axis = 1)

shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,Others
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,Others
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,Surfing
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,Surfing
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,diving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y,Diving
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y,diving
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y,Swimming
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y,Others
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,Swimming

In [371]:
set(shark_attacks_v3['Activity_adjusted'])

{'Boat',
 'Boating',
 'Canada',
 'Canoe',
 'Canoeing',
 'Dived',
 'Diving',
 'Feeding',
 'Feeling',
 'Fishing',
 'Fishingat',
 'Kayaking',
 'Kite',
 'Kiteboarding',
 'Others',
 'Raytheon',
 'Royal',
 'Ship',
 'Shipwreck',
 'Shipwrecked',
 'Skiing',
 'Skimboarding',
 'Surf',
 'Surfing',
 'Surfng',
 'Swimming',
 'Wakeboarding',
 'banana',
 'bananas',
 'boat',
 'boating',
 'boats',
 'caft',
 'canoe',
 'canoeing',
 'canoes',
 'containing',
 'contract',
 'dive',
 'dived',
 'diver',
 'divers',
 'divians',
 'diving',
 'fed',
 'feeding',
 'feel',
 'feet',
 'fishing',
 'fishingat',
 'kite',
 'raft',
 'rafts',
 'rant',
 'roat',
 'ronaut',
 'rontenac',
 'ship',
 'shipmate',
 'shipmates',
 'ships',
 'shipwreck',
 'shipwrecked',
 'ski',
 'skiff',
 'skiing',
 'surf',
 'surface',
 'surfboard',
 'surfboat',
 'surfing',
 'surfmat',
 'swim',
 'swimming',
 'swimmng'}

In [376]:
"""
It is clear that we reduced the problem to some categories. Let's refine it.
"""

shark_attacks['Activity'] = shark_attacks['Activity'].astype(str).str.lower()

def activity_classifier(row):
    """
    This function will classify the rows present in columns 'Activity' based on a list of strings set before.  
    """
    
    feeding_match_list = re.findall('[f][e][e][d].*[s][h][a]', row['Activity'])
    fishing_match_list = re.findall('[f][i][s][h][i]', row['Activity'])
    diving_match_list = re.findall('[d][i][v]', row['Activity'])
    surfing_match_list = re.findall('[s][u][r][f]', row['Activity'])
    swimming_match_list = re.findall('[s][w][i][m]', row['Activity'])
    parasailing_match_list = re.findall('[p][a][r][a][s][a][i][l]', row['Activity'])
    skiing_match_list = re.findall('[s][k][i]', row['Activity'])
    wake_match_list = re.findall('[w][a][k][e]', row['Activity'])
    kite_match_list = re.findall('[k][i][t][e]', row['Activity'])
    boating_match_list = re.findall('[kcrb][ao][ynfa][aot]', row['Activity'])
    motorized_match_list = re.findall('[ys][ah][ti][cp][h]?', row['Activity'])
    
    if  len(feeding_match_list) != 0:
        return feeding_match_list[0]
    
    elif len(fishing_match_list) != 0:
        return fishing_match_list[0]
    
    elif  len(diving_match_list) != 0:
        return diving_match_list[0]
        
    elif len(surfing_match_list) != 0:
        return surfing_match_list[0]
        
    elif len(swimming_match_list) != 0:
        return swimming_match_list[0]
    
    elif len(parasailing_match_list) != 0:
        return parasailing_match_list[0]
    
    elif len(skiing_match_list) != 0:
        return skiing_match_list[0]
    
    elif len(wake_match_list) !=0:
        return wake_match_list[0]
    
    elif len(kite_match_list) !=0:
        return kite_match_list[0]
    
    elif len(boating_match_list) != 0:
        return boating_match_list[0]
    
    elif len(motorized_match_list) != 0:
        return motorized_match_list[0]
    
    else:
        return 'other activities'

    
shark_attacks_v3['Activity_adjusted'] = shark_attacks.apply(activity_classifier, axis = 1)

shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,other activities
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,other activities
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,surf
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,surf
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,div
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y,div
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y,div
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y,swim
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y,other activities
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,swim

In [377]:
set(shark_attacks_v3['Activity_adjusted'])

{'bana',
 'boat',
 'caft',
 'cana',
 'cano',
 'cont',
 'div',
 "feeding 2.5' to 5\x92 sha",
 'feeding a sha',
 'feeding captive sha',
 'feeding mullet to sha',
 'feeding prawns to captive sha',
 'feeding sha',
 'feeding the sha',
 'fishi',
 'kaya',
 'kite',
 'other activities',
 'raft',
 'rant',
 'rayt',
 'roat',
 'rona',
 'ront',
 'roya',
 'ship',
 'ski',
 'surf',
 'swim',
 'wake'}

In [378]:
"""
Now that we narrowed down, we will classify them.
"""

shark_attacks['Activity'] = shark_attacks['Activity'].astype(str).str.lower()

def activity_classifier(row):
    """
    This function will classify the rows present in columns 'Activity' based on a list of strings set before.  
    """
    
    feeding_match_list = re.findall('[f][e][e[d].*[s][h][a]', row['Activity'])
    fishing_match_list = re.findall('[f][i][s][h][i]', row['Activity'])
    diving_match_list = re.findall('[d][i][v]', row['Activity'])
    surfing_match_list = re.findall('[s][u][r][f]', row['Activity'])
    swimming_match_list = re.findall('[s][w][i][m]', row['Activity'])
    parasailing_match_list = re.findall('[p][a][r][a][s][a][i][l]', row['Activity'])
    skiing_match_list = re.findall('[s][k][i]', row['Activity'])
    wake_match_list = re.findall('[w][a][k][e]', row['Activity'])
    kite_match_list = re.findall('[k][i][t][e]', row['Activity'])
    boating_match_list = re.findall('[kcrb][ao][ynfa][aot]', row['Activity'])
    motorized_match_list = re.findall('[ys][ah][ti][cp][h]?', row['Activity'])
    
    if  len(feeding_match_list) != 0:
        return 'feeding'
    
    elif len(fishing_match_list) != 0:
        return 'fishing'
                
    elif  len(diving_match_list) != 0:
        return 'diving'
        
    elif len(surfing_match_list) != 0:
        return 'surfing'
        
    elif len(swimming_match_list) != 0:
        return 'swimming'
    
    elif len(parasailing_match_list) != 0:
        return 'parasailing'
    
    elif len(skiing_match_list) != 0:
        return 'skiing'
    
    elif len(wake_match_list) !=0:
        return 'wake'
    
    elif len(kite_match_list) !=0:
        return 'kite'
    
    elif len(boating_match_list) != 0:
        return 'boating'
    
    elif len(motorized_match_list) != 0:
        return 'yatching/ship'
    
    else:
        return 'other activities'

    
shark_attacks_v3['Activity_adjusted'] = shark_attacks.apply(activity_classifier, axis = 1)

shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,other activities
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,other activities
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,surfing
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,surfing
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,diving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y,diving
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y,diving
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y,swimming
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y,other activities
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,swimming

In [379]:
set(shark_attacks_v3['Activity_adjusted'])

{'boating',
 'diving',
 'feeding',
 'fishing',
 'kite',
 'other activities',
 'skiing',
 'surfing',
 'swimming',
 'wake',
 'yatching/ship'}

In [382]:
# Let's check the results of the classification.

shark_attacks_v3[shark_attacks_v3['Activity_adjusted'] == 'feeding']

# In general it's pretty good.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN,N,feeding
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,34,Shallow lacerations to finger PROVOKED INCIDENT,N,NaN,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN,N,feeding
132,2017.06.14.R,Reported 14-Jun-2017,2017.0,Unprovoked,BAHAMAS,NaN,NaN,Feeding sharks,Carly,F,NaN,Fingernail pulled off,N,NaN,NaN,"AOL.UK, 6/14/2017",2017.06.14.R-Carly.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.14.R,2017.06.14.R,6171.0,NaN,NaN,N,feeding
140,2017.05.28,28-May-2017,2017.0,Unprovoked,USA,Florida,Off Jupiter,Feeding sharks,Randy Jordan,M,NaN,Lacerations to right arm,N,Morning,Tiger shark,"M. Michaelson, GSAF",2017.05.28-Jordan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.05.28,2017.05.28,6163.0,NaN,NaN,N,feeding
442,2015.03.16,16-Mar-2015,2015.0,Unprovoked,FRENCH POLYNESIA,Bora Bora,Anau,Hand feeding sharks,male,M,9,Hand bitten,N,10h00,Blacktip shark,"Radio1, 3/16/2015",2015.03.16-Bora-Bora.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.03.16,2015.03.16,5861.0,NaN,NaN,N,feeding
811,2012.03.06.a,06-Mar-2012,2012.0,Provoked,AUSTRALIA,Victoria,"Shipwreck Cove, Melbourne Aquarium","Diving, feeding sharks",female,F,34,Superficial lacerations to right side of face ...,N,11h30,"Tawny nurse shark, 40cm","The Age, 3/6/2012",2012.03.06.a-MelbourneAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.03.06.a,2012.03.06.a,5492.0,NaN,NaN,N,feeding
2073,2000.02.14,14-Feb-2000,2000.0,Provoked,ENGLAND,Worcestershire,The Fountain Pub in Tenbury Wells,Feeding prawns to captive sharks,"Paul Smith, a chef",M,NaN,Fingers bitten PROVOKED INCIDENT,N,NaN,"Miami, a 60 cm blacktip shark and two 60 cm b...","The Sun (London), 2/17/2000",2000.02.14-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.02.14,2000.02.14,4230.0,NaN,NaN,N,feeding
2701,1989.00.00.b,1989,1989.0,Unprovoked,PAPUA NEW GUINEA,New Ireland,Kavieng,"Scuba diving, hand feeding sharks",Dinah Halstead,F,NaN,Thigh & calf bitten,N,NaN,7' silvertip shark,"S. Waterman, GSAF",1989.00.00.b-Halstead,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1989.00.00.b,1989.00.00.b,3602.0,NaN,NaN,N,feeding
3200,1975.12.02,02-Dec-1975,1975.0,Provoked,AUSTRALIA,New South Wales,"Porpoise Pool, Tweed Heads",Filming & feeding captive sharks,John Strand,M,35,Tooth mark in left elbow PROVOKED INCIDENT,N,NaN,"Grey nurse shark, 10'","J. Green, p.36",1975.12.02-Strand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.12.02,1975.12.02,3103.0,NaN,NaN,N,feeding
3235,1975.03.13,13-Mar-1975,1975.0,Provoked,AUSTRALIA,Queensland,Southport Aquarium,Diving & force-feeding the shark,William Hookway,NaN,18,Laceration to thigh by captive shark PROVOKED ...,N,NaN,"Bronze whaler shark, 6'","The Age, 3/14/1975",1975.03.13-Hookway.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.03.13,1975.03.13,3068.0,NaN,NaN,N,feeding
3446,1968.12.26,26-Dec-1968,1968.0,Provoked,AUSTRALIA,New South Wales,"Marineland Aquarium, Manley, Sydney",Feeding mullet to sharks,Peter Jones,M,27,Laceration to finger by a captive shark PROVOK...,N,Morning,"Grey nurse shark, 10'","The Age, 12/27/1968",1968.12.26-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.12.26,1968.12.26,2857.0,NaN,NaN,N,feeding
3527,1967.05.09,09-May-1967,1967.0,Provoked,AUSTRALIA,NaN,Aquarium,Feeding a shark,Rod Stanley,M,22,Recorded as PROVOKED INCIDENT,N,Afternoon,Grey nurse shark,H.D.Baldridge (1994) SAF Case #1536,1967.05.09-NV-Stanley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1967.05.09,1967.05.09,2776.0,NaN,NaN,N,feeding
4049,1959.11.10,10-Nov-1959,1959.0,Unprovoked,USA,California,"Near Paradise Cove, Malibu, Los Angeles County",Swimming at surface through school of feeding ...,Duffie Fryling,M,21,Forearm bitten,N,10h30 or 13h30,"Blue shark, 1.5 m [5']","D. Miller & R. Collier; R. Collier, pp.26-27; ...",1959.11.10-Fryling_Collier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1959.11.10,1959.11.10,2254.0,NaN,NaN,N,feeding
4720,1942.00.00.k,1942,1942.0,Sea Disaster,INDONESIA,East Java,Surabaya,Captured Allied soldiers were squeezed into 3'...,200 soldiers,M,NaN,"General Imamura, Commander in Chief of Japanes...",Y,NaN,NaN,G. Duncan,1942.00.00.k-PigBasketAtrocity.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.k,1942.00.00.k,1583.0,NaN,NaN,Y,feeding
5131,1927.02.14,14-Feb-1927,1927.0,Provoked,NICARAGUA,Salinas Bay,"A shark was caught, its head severed from body...",Feeling the sharks teeth,a sailor,M,NaN,"Sharkss jaws snapped shut, lacerating his rig...",N,NaN,NaN,"G.A. Llano, p.178",1927.02.14-sailor.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.02.14,1927.02.14,1172.0,NaN,NaN,N,feeding

In [383]:
shark_attacks_v3[shark_attacks_v3['Activity_adjusted'] == 'feeding'].shape

(15, 26)

## Conclusion

In [395]:
# We managed to filter down all the entries into feeding sharks.
# Now we can divide by the number of valid total entries and get the % shark incidents.

feeding_attacks_perc = round(15/6200*100, 2)

print(f'The percentage share of attacks while feeding sharks during the timespan is {feeding_attacks_perc}%.')

The percentage share of attacks while feeding sharks during the timespan is 0.42%.

In [396]:
# In parallel, the % of attacks during diving is:
shark_attacks_v3[shark_attacks_v3['Activity_adjusted'] == 'diving'].shape

(543, 26)

In [399]:
diving_attacks_perc = round(543/6200*100, 2)

print(f'The percentage share of attacks while feeding sharks during the timespan is {diving_attacks_perc}%.')
print("Therefore, the chance of a shark attack while feeding them is lower than diving itself.")

The percentage share of attacks while feeding sharks during the timespan is 8.76%.
Therefore, the chance of a shark attack while feeding them is lower than diving itself.