# Importing relevant libraries

In [4]:
import pandas as pd
import numpy as np

# Importing data

In [5]:
shark_attacks = pd.read_csv('C:/Users/pfaprado/Documents/IronHack/2021-01-22-project-shark-attack/attacks.csv', encoding='latin1')

# Preliminary analysis of data

In [6]:
shark_attacks.size

# We have about 617352 elementos na tabela.

617352

In [7]:
shark_attacks.shape

# We have 24723 entries of 24 types of data.

(25723, 24)

In [8]:
shark_attacks.info()

# Too many data entries without many infos such as Age, Time, Sex, Fatal, etc. Last columns can't be used.
# Year is a float64, should have been an integer.
# Age should have been specified as integer.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [40]:
# Specifically, about the types of data columns.

shark_attacks.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

In [24]:
# Let's show all the columns available through a max_columns and a head method.

pd.options.display.max_columns = None
shark_attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [25]:
# All the columns availables.

shark_attacks.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [10]:
# Let's count all the occurrences present in the column Fatal.

shark_attacks['Fatal (Y/N)'].value_counts()

# Highest portion of shark attacks are non-fatal.

N          4293
Y          1388
UNKNOWN      71
 N            7
2017          1
N             1
y             1
M             1
Name: Fatal (Y/N), dtype: int64

In [11]:
shark_attacks['Activity'].value_counts()

# Highest portion occurred during surfing, swimming or fishing.
# !However there are way too many categories to affirm anything at this point!

Surfing                                                             971
Swimming                                                            869
Fishing                                                             431
Spearfishing                                                        333
Bathing                                                             162
                                                                   ...
Swimming near canoe                                                   1
Swimming near life raft                                               1
Boeing 757 enroute from Porta Plata plunged into the sea              1
Lifesaving exhibition                                                 1
The passenger ship Pioneer Cebu  capsized & sank in Typhoon Irma      1
Name: Activity, Length: 1532, dtype: int64

# Jaws Adventures: marketing shark feeding

In [18]:
"""
Our company, "Jaws Adventures", offers scuba diving and free diving for people.
We would like to analyse and market a new product: shark feeding.
However people may express distress to the idea of feeding sharks and the risks involved.
Let's analyse whether feeding sharks is safer than other activities such as swimming, for example.
"""

"""
For this, we will need to pull the data from columns:
- Activity (categorical)
- Fatal (Y/N) (categorical, binary: Y/N)
This data will represent all kinds of attacks registered.

However, we know that the database is kind of sketchy, so we will need to do some data wrangling (cleaning) before.
"""

fatality_activity = shark_attacks[['Activity','Fatal (Y/N)']]

fatality_activity

          Activity Fatal (Y/N)
0         Paddling           N
1         Standing           N
2          Surfing           N
3          Surfing           N
4      Free diving           N
...            ...         ...
25718          NaN         NaN
25719          NaN         NaN
25720          NaN         NaN
25721          NaN         NaN
25722          NaN         NaN

[25723 rows x 2 columns]

In [28]:
# Let's check how many nulls we have in our dataset in each column.

null_cols = shark_attacks.isnull().sum()

null_cols

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

In [38]:
# Let's understand the cases where the entries are null for Activity.

null_display = shark_attacks[shark_attacks['Activity'].isnull() == True]
null_display

# There is no apparent reason or correlation between null entries of Activity to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
47,2018.01.28,28-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,male,M,18,Injuries to right leg,N,08h00,Bull shark,"ABC.net.au, 01/28/2018",2018.01.28-ConeBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.28,2018.01.28,6256.0,NaN,NaN
108,2017.07.29.a,29-Jul-2017,2017.0,Unprovoked,USA,South Carolina,"DeBordieu Colony, Georgetown County",NaN,female x 2,F,12,Bite to left thigh / minor injury,N,Afternoon,NaN,"C. Creswell, GSAF",2017.07.29.a-Georgetown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.a,2017.07.29.a,6195.0,NaN,NaN
112,2017.07.23.b,23-Jul-2017,2017.0,Unprovoked,USA,New Jersey,Ventnor,NaN,Isabella Smith,F,NaN,Minor injury to hand,N,NaN,Sandtiger shark 2',A. Smith,2017.07.23.b-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.23.b,2017.07.23.b,6191.0,NaN,NaN
114,2017.07.22,22-Jul-2017,2017.0,Unprovoked,USA,Florida,"Snipes Point, Monroe County",NaN,female,F,40,Foot bitten,N,12h30,"""A small shark""","NBC Miami, 7/23/2017",2017.07.22-Keys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.22,2017.07.22,6189.0,NaN,NaN
154,2017.04.17.b,17-Apr-2017,2017.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,NaN,NaN,NaN,Minor bite to the foot,N,Afternoon,NaN,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# Let's understand the cases where the entries are null for Fatal.

null_display2 = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display2

# There is no apparent reason or correlation between null entries of Fatal to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,CastellÃ³n,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# We previously noticed that year and age were float and object, respectively.
# Let's make them both integer.

# shark_attacks['Year'] = shark_attacks['Year'].astype('int')

# shark_attacks['Year'].dtype

In [45]:
# Let's check for duplicates in our database and remove them:

before = len(shark_attacks)
shark_attacks = shark_attacks.drop_duplicates()
after = len(shark_attacks)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  19411

In [46]:
# That's how our database is now:

shark_attacks

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0,NaN,NaN
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0,NaN,NaN
6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Cleaning: 'Fatal (Y/N)'

In [94]:
# Let's check the unique values of the column Fatal (Y/N) and its incidence in our database.

print(f"""
These are the occurrences of the values for Fatal (Y/N):
{shark_attacks['Fatal (Y/N)'].value_counts()}
""")

print(f"""
These are the unique values of the Fatal (Y/N) column:
{set(shark_attacks['Fatal (Y/N)'])}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.
""")

These are the occurrences of the values for Fatal (Y/N):
N          4293
Y          1388
UNKNOWN      71
 N            7
y             1
M             1
N             1
2017          1
Name: Fatal (Y/N), dtype: int64


These are the unique values of the Fatal (Y/N) column:
{'Y', nan, 'N ', 'M', '2017', 'y', 'N', 'UNKNOWN', ' N'}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.

### Uniques check exercise.

In [99]:
#Let's examine the case of 2017.

shark_attacks.loc(shark_attacks['Fatal (Y/N)'] == 2017)

TypeError: 'Series' objects are mutable, thus they cannot be hashed

### Row dropping

### Transform the dataframe series into a list.

In [79]:
# 1.Transform the dataframe series into a list.

fatal_list = list(shark_attacks['Fatal (Y/N)'])

#shark_attacks['Fatal (Y/N)'] = shark_attacks[shark_attacks['Fatal (Y/N)'] == 'N ' | ]
#shark_attacks['Fatal (Y/N)'] = shark_attacks.query('Fatal (Y/N)' == " N" and Cylinders >= 6 and `Combined MPG` < 18')

### Upper case the strings.

In [81]:
# 2. Upper case the strings.

# Since we have a list of strings, we can only upper case them once we treat each one exclusively,
# given that upper() is a method of strings. We can, however, create a list comprehension to treat
# every string individually like is done in a loop.

fatal_list = [ element.upper() for element in fatal_list]

fatal_list

AttributeError: 'float' object has no attribute 'upper'

In [ ]:
# There are some values for N that have spaces after or before them. We cant strip these spaces in the entries.

In [48]:
# Let's check the unique values of the column Activity.

print(set(shark_attacks['Activity']))

# It's definetely chaotic and somewhat anedoctal (too many descriptions).
# We will have to categorize them better, maybe through bins.

{nan, 'Among 31 survivors of crew from the sampan Fukulya Maru (which reached Thursday Island in rowing boat) was a man whose arm had been bitten off by shark. The sampan wrecked west of McArthur island ', "Fishing from 34' boat when pulled overboard by hooked shark", 'Went over side of boat at trochus ground', 'British ship Macedon was thrown on her beam ends by a sudden squall', 'Scuba diving & U/W photography', 'Fell overboard while fishing for sharks', '25-foot cabin cruiser Happy Jack sank in heavy seas', 'Standing / Bathing', 'The MV Dona Marilyn sank in Typhoon Unsang with the loss of 389 lives', 'Fishing for perch', 'Cruising', 'Fishing (trolling)  from canoe', 'Landing hooked shark in boat', 'Hunting seashells', 'Traveling by boat', 'Swimming near pier', 'Standing in knee-deep water', "Accidentally stood on hooked shark's tail before attempting to gut it ", 'Floating on an inflatable raft', '"Boat accident"', 'Shark tagging', 'Thrown from destroyer when shell hit', 'Fell overboard from USS Ward', 'Wreck of the Storm King', 'Killing a shark', 'Fishing, holding fish', 'Crossing inlet in a boat, seen fighting sharks with his oar, sharks smashed boat', 'Sea disaster : Wreck of the Taiaroa', 'Swimming from the New Venture ', 'Jumped or fell overboard', 'Pacific Seafarer of US Navy', 'Fishing from shore, washed into the sea', 'Swimming to shore after a squall  capsized their motorized shark fishing boat', 'Hurricane & Tidal Wave', 'Wade-fishing', 'Preparing to fish for jack-mackerel', 'Fishing (rod & line)', 'Swimming (lead swimmer in race)', 'Fishing, wading with string of fish', 'Swimming 3 miles offshore', 'Sinking of the ferryboat Dumaguete ', 'Free diving / Spearfishingat edge of reef', 'Touching the mouth of a supposedly dead shark', 'Swimming or Snorkeling', 'Bathing in water 0.9 m deep', 'Free diving, collecting shells', 'Holding onto an inflatable boat', 'Fell onto dead shark', 'Adrift after the sinking of the motor yacht Princess Dianne', 'Wading (shrimping)', 'Attempting to illegally enter the USA', 'Swept off deck of S.S.Frontenac enroute from West Indies to US', 'Fishing for blue sharks', 'Fell oveboard', 'Spearfishing, but swimming at surface', 'Capsized fishing boat', 'Free diving & spearfishing (ascending)', 'Collecting crayfish', 'Spearfishing / swimming on surface', 'boat from ship Josephine capsized in squall', 'In deep water about 100 yards from his ship', 'Feeding stingrays?', 'Surfing / Swimming', 'Cleaning the side of a ship', 'Suicide', 'Kayak fishing', 'Racing ski', 'Feeling the shark\x92s teeth', 'Closed circuit diving (submerged). Diving to recover jettisoned packets of opium for police', 'Teasing a shark', 'Exercising his dog in the shallows', 'Diving from canoe', 'Standing or boogie boardin', 'Free-diving', 'The Cuban freighter Libertad was torpedoed and sunk by the German submarine U-129', 'Watching seine netters with friends, one of whom picked up a netted shark', 'Floating on air mattress', 'In water with diving seabirds', 'Hunting turtle', 'Collecting fish in military trap when bitten by captured shark that had been shot by soldiers with Garten', '3 men & 2 boys picked up wearing life jackets and with inner tube', 'Hunting seals', 'Argentine Air Force C-54', 'Finning the shark that bit him', 'British patrol boat 1250-ton HMS  Valerian foundered in a hurricane', 'Surfing ', 'American minesweeper USS YMS-350 lost in a typhoon - swimming to shore', 'Playing in the water', 'Lifesaving drill', 'Knocked into the water', 'Windsurfing (urinating on his board)', 'Boarding a ship', 'Resting on surfboard', 'Collecting aquarium specimens', 'Standing in chest-deep water', "Lying prone in 2' of water", 'Spearfishing, carrying fish on spear', 'Freediving for trochus shell (submerged)', 'The coastwise steamer San Basilio capsized in a typhoon', 'Escaping from Alacatraz', 'Man fell overboard from ship. Those on board threw a rope to him with a wooden block & were pulling him to the ship', 'Transatlantic Rowing', 'Yacht race', 'Tandem surfing', 'Explosion & sinking of the USS Juneau after being torpedoed by the submarine  I-85', 'Crew swimming alongside their anchored ship', 'Dynamiting fish', 'Playing with an air mattress', 'Attempting to chase shark out to sea', 'Jumping', 'Adrift on refugee raft', 'Spearfishing, pulled shark\x92s tail', 'Bathing or body surfing ', 'Testing anti-shark cage', 'Swimming / Wading', 'Swimming, when caught in heavy seas', 'Dog paddling or standing', 'Hunting crayfish ', 'Wreck of the steamship Birkenhead', 'Steamer Una wrecked with 75 laborers onboard. Survivors took to rafts & lifeboats.', 'Free diving / Photographing pilot whales', 'Scuba Diving for lobster (at surface)', 'Commercial spearfishing', 'Swimming or paddle boarding', 'Sinking of the M/V Mindoro during a typhoon', 'Fell overboard from fishing schooner Halycon', 'Aircraft ditched in the sea, swimming ashore', 'Fishing, hooked shark towed boat out to sea, storm swamped boat', 'Lying on surfboard', 'Removing shark from net', 'Spearfishing & lassoed shark', 'Greek steamship Lakonia caught fire, 98 of her 646 passengers, and 30 of her crew of 376 perished', 'Hiking on the beach', 'R5D aircraft went down with 29 on board', 'Pleasure boating', 'Swimming ashore after launch capsized', 'SCUBA diving', "Fishing, removing gaff from shark's mouth", 'Body boarding ', 'Spearfishing with Joe Turner (24). Shark attracted to speared halibut on belt of one diver, tried to bite Ide\x92s speargun & he shot it in the mouth', 'Scuba diving & spearfishing', 'Adrift on a raft ', 'Beach seine netting', 'A father bathing his smallest daughter when the shark bumped her out of his arms and carried her into deep water', 'The boat Caribou II sank', 'Knocked overboard', 'Fishing with hand line tied to wrist & was pulled into the water', 'Wreck of the tug Magellan', 'Swimming around anchored ship', 'Swimming alongside the schooner Catherine Wilcox', 'Lobstering', 'Fishing for mackerel', 'Free diving or wading back to shore', 'Fishing, on a boat', 'yachting accident', 'Surf skiing ', 'Wreck of a sampam', 'Scooping prawns', 'Playing / jumping', 'Surfing with dolphins', 'Fell overboard from the Selim', 'HBM Magpie foundered in a squall', 'Fishing for kob', 'Tzenny Chandris, a Greek freighter laden with scrap iron, foundered in heavy weather', 'Standing, collecting sea stars', 'Swimming from camp', "Swimming near jetty with 2' piece of wood", 'Attempting to remove fishing net from submerged object', 'Bodyboarding', 'Bathing alongside US Naval ship', 'Fishing from rocks, swept out to sea by large wave & treading water', 'Surfing, fell off surfboard', 'Swimming ashore from swamped 13-ft boat', 'Boat capsized, clinging to line', 'ship M.V. Rizal sank during typhoon', 'Paddling on surfboard', 'Sea disaster, wreck of the Alfred Watts', 'Disappeared 11 days earlier, probable homicide victim', 'Feeding fish', 'Playing with a frisbee in the shallows', 'Dived overboard & was swimming near stern of trawler', "Fishing from 32' boat", 'Swimming in fish tank', 'Swept out to sea by the tsunami, she clung  to a log for 24 hours', 'boat capsized during filming', 'Lobster diving using Scuba', 'Skimboarding', 'The inter-island ferry Vula sank in heavy weather', 'Fishing in knee-deep water', 'Inspecting teeth of supposedly dead (hooked & shot) shark', 'Carrying a supposedly dead shark by its mouth', '3,909-ton Panamanian freighter Chieh Lee sank in a typhoon', 'Working near fish traps', '"Climbing up to ship after repairing the stern in water"', 'Fishing, two large sharks passed. He speared one and it bit him', 'Reviving a sedated shark', 'Fishing boat swamped in storm', "Fell off surfboard 20' from shore", "Skin diving. Grabbed shark's tail; shark turned & grabbed diver's ankle & began towing him to deep water", 'Scuba diving, hand feeding sharks', 'Taking catch from a fish weir in which the shark was snared', 'Lifeboat capsized', 'Diving from dinghy for trochus shell', 'Kite-Boarding', 'Boat capsized, swimming to shore', 'Sea disaster, wreck of the sloop Sara', 'Commercial Salvage Diving', 'Free diving, carrying speargun', 'British cruiser Dunedin torpedoed & sunk by the U-124', 'Testing movie camera in full diving dress', "Boat capsized between O'ahu & Molokai", 'Free diving with goggles', 'Diving for pearl', 'Bathing / standing', 'Swimming underneath house on pilings', 'Sea Disaster, sinking of the motorship Wingate', 'Spearfishing, shot a turtle', 'Fishing for shrimp', 'Playing on rock, slipped & fell into the water', 'Attempting to escape by swimming to shore', 'Aircraft exploded', 'Cutter capsized', 'Night bathing', 'Skindiving', 'Leaving the water', 'Spearfishing (but on surface)', 'Swimming / jumping off a jetty', 'Working on the bridge when he fell into the river', 'Clinging to shipwrecked junk', 'Jumped off rocks into white water', 'Scallop diving (using surface-supplied air & a POD) ', "Adrift, hanging onto cushion, after his 17' skiff ran out of gas & capsized 3 miles from shore", 'Went overboard', 'Underwater photography', 'Abalone diving using Hookah (resting on the surface)', 'Playing on a sandbar', 'S2N Navy scout plane went down, E.H. Almond & Lieut A.G. Reading in water', 'Fishing schooner Jose Luis foundered', 'Swimming from naptha launch after a day of fishing', 'Swimming with goggles', 'Jumped overboard to rescue companion', 'Surfing, but treading water', 'Collecting shells', 'Moving a shark in a net ', 'Spearfishing on scuba', 'Hardhat diving from Japanese pearling lugger, Reiyo Maru', 'Swimming, carrying tin can with mail to steamer', 'Washing horses', 'Dived naked into the water on a bet', 'Fishing boat swamped in a storm', 'Fishing  (trawling)', 'Snorkeling, possibly holding a fish', 'Spearfishing, free diving, possibly ascended into path of cruising shark', 'Fishing, hauling in net, shark in net', 'Diving for coins tossed from passenger ship', 'Fell overboard  from the Taiwanese fishing trawler Lien Cheng Feu ', 'Hauling dead shark aboard, when another shark leapt out of the water & bit him', 'Boat swamped', 'Wading & pushing dinghy toward  the shallows', 'Swimming, attacked at  surf carnival', 'Shooting sharks ', 'Boeing 757 enroute from Porta Plata plunged into the sea', 'Swimming near life raft', 'Swimming near canoe', 'Swimming / treading water', 'Surf fishing, wading ', 'Free diving, collecting sand dollars', 'Hookah diving for pen shells ', 'Sea disaster, foundering of the cargo vessle M/V Dorolonda', 'Free diving (but on surface)', 'Feeding mullet to sharks', 'Free diving & spearfishing (descending)', 'Playing ', 'Free diving with a pod of dolphins', 'Bathing in river', 'Fishing, boat capsized', 'Hard hat diving', '4 men were bathing', 'Fell off banana boat', 'Boogie boarding or Surfing', 'Scuba diving for bivalves', 'Fishing for the shark that killed George Lundberg', 'Paddle-surfing', 'Swimming breast stoke', 'Spearfishing (but treading water on the surface)', 'Trailing hand in the water', 'Wreck of  large double sailing canoe', 'Seine netting', 'Sinking of the ferryboat Don Juan', 'Netting pilchards', 'Diving off wharf', 'Freediving for seashells', 'Diving for sand dollars', "Fishing - 'tag & release'", '13 men in the water after sailboat capsized & sank', 'Fishing / diving', "Spearfishing, holding 5' speared fish", 'Net fishing, fell into the water', 'Sea Disaster : Wreck of the Carrie E. Long', 'Diving', 'Wade Fishing', 'Known as The Battle of the Bismarck Sea :  8 Japanese destroyers guarding a convoy of 8 transports were attacked by 129 Allied fighters, 207 bombers & 3 squadrons of the Royal Australian Air Force. ', 'Attempting to net shark in shark channel', "Fishing, caught a 15' shark & took it onboard", 'Fishing for tarpon', 'Walking out of the water after surfing', 'Body surfing & treading water', 'Catching a turtle', 'Diving?', 'The steamship Bonnie Dundee lost in collision', 'Diving for pen shells', 'American cruiser Indianapolis torpedoed & sunk by the Japanese submarine I-58', 'Helmet diving', 'Walking in chest-deep water', 'Body surfing?', 'Washing clothes', 'Spearfishing, hunting crayfish', 'Paddling a canoe', 'Their 9 m launch was run down by a 25,000-ton Japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days', 'Net fishing', 'Drift fishing', 'Seining for bait, standing in chest-deep water', 'Sea Disaster, sinking of the fishing  launch Mavis', 'Scuba Diving for scallops', 'Swimming ashore from capsized boat', 'Standing, washing rear wheels of his ambulance in ankle-deep water', 'Swimming alongside NOAA research vessel Discoverer', 'Swimming, poaching abalone', 'Swimming with fish attached to  belt', 'Fell oveboard from steamer Wanderer', "12 of the Penang's crew were returning to the ship when their 12' dinghy capsized", 'Free diving for molluscs', 'Wakeboarding', 'Surfing, but lying prone on his board', 'Swimming. Passer-by, Len Bedford, heard him shriek , saw shark leap from the water & swimmer disappeared', 'Dragging banana seeds through the shallows', 'Swimming near jetty', 'Watching seals', 'Washed into sea while picking opihi & attacked by 2 large sharks ', 'Spearfishing', 'Scuba diving, reportedly also spearfishing', 'Jumped overboard from Norwegian steamship Venator', 'Skindiving for abalone (but at surface)', 'Treading water after survivng crash of the US Navy airship K-74 that was hit by the German submarine U-134', 'Standing in water with child in her arms', 'Standing / Wading', "Swimming at surface through school of feeding 2.5' to 5\x92 sharks", 'Swimming to shore from the Medic', 'Fleet of canoes caught by a squall and charged by sharks.', 'Kite boarding', 'Fell into the water', 'Spearfishing or fishing', 'Small boat with 2 men onboard hit a submerged coral formation. Men began swimming to shore', 'Spearfishing & had just speared a ulua', 'Swimming after his hat', 'Net fishing, picking catch from the net', 'Fishing from launch, fell into net with shark', 'Surf fishing in waist-deep water', "Bathing in 3' to 4' of water", 'Inebriated, woke from sleep and fell off deck into the water ', 'Crossing the bay at the ford', 'Air disaster', 'Spearfishing, dived to pick up a float line', 'Sitting in a boat', 'Body surfing / treading water', 'Dived from inner-tube', 'Washed overboard into school of fish', 'Fishing, Struck by another shark when removing shark from line', 'Fell into water while attempting to boat a swordfish', 'Swimming out to rescue swimmers in difficulty', 'Spearfishing, had fish on his spear', 'Helping men land a shark', 'Boat of the Resolution capsized in the breakers', 'Fishing with a cast net', 'Jumped into the water', 'Attempting to set underwater endurance record', 'Swimming outside the safety enclosure attempting to retrieve a tennis ball drifting toward midstream ', 'Lying prone on surfboard', 'Dived overboard to retrieve dinghy', 'Air disaster: crash of Air France Super Constellation ', 'Lying on surfboard & paddling', '"Crossing the river"', 'Swimming, after falling overboard', 'Gaffing netted shark', 'Japanese POW ship Arisan Maru with 1800 American prisoners of war on board bound for slave labor camps was torpedoed by an American submarine', 'Treading water/ Surfing', 'Shrimping', 'Working prawn net', 'Swimming, towing the shark', 'Diving, retrieving fish caught in net ', 'Attempting to rescue an injured & beached shark', 'Diving (shell maintenance)', 'Bathing with her mother', 'Kite Boarding', 'Dutch merchant ship Zaandam torpedoed  by the U-174 amidships, sank & dozens of survivors took to rafts & boats. One man, Izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down', 'Hunting crayfish', 'Ascending from a dive', 'Playing soccer in the water', 'Spearfishing, but standing in knee-deep water', 'Watching the shark feeding on a dead pinniped', 'Two canoes with 14 aboard blown to sea in a storm. While adrift for 3 week, one person fell overboard and was killed by a shark', 'Spearfishing, speared fish retreated to cave where shark grabbed his arm', 'Fell overboard?', 'Fishing from Surfboard', 'The 500-ton coastal trader Polurrian foundered ', 'ship William Penn grounded & broke apart', 'Free diving for trochus', 'Spearfishing / freediving', 'Small vessel with 13 men on board capsized crossing the bar and 6 men drowned.  The 7 survivors were swimming to shore', 'Collecting beche-de-mer', 'Harassing a shark', 'Spearfishing on Scuba', 'Wading in school of baitfish', 'Spearfishing / Free diving', 'Sitting in the water', 'Fishing, one of three fishermen swept into the sea by a large wave ', 'Checking fish traps, fell into the water', 'Swimming ashore from fishing boat swamped and sunk by a squall', 'Diving & fishing with net', 'Windsurfing, but sitting on his board', 'Shark watching', 'Pulling hooked salmon to boat', 'Wading, netting fish', 'Scuba diving ', 'Fishing for white sharks', 'Surf fishing', 'The USS Wahoo torpedoes & sank the Japanese troop transport Buyo Maru', 'Shark fishing', 'Fishingat', 'Placed hand in disemboweled shark\x92s jaws', 'Fishing, catching snoek, Thyrsites atun', 'yachtsman in a zodiac', 'The schooner Tahitienne foundered in a hurricane', 'Fishing in shoulder-deep water', 'Floating on a small orange raft ', 'U-177 torpedoed & sank the troopship Nova Scotia', 'Sculling', 'Swimming in midriver near sewage outlet & 400 m from a slaughterhouse', 'Standing / surfing', 'Free diving / spearfishing, from paddleboard & floating on the surface', 'Scuba diving & filming', 'Fishing, walking in river to cast', 'Sailing on catamaran & fell into the water', 'Steinhart Aquarium', 'Swimming with boogie board', 'After rowing skiff was holed by shark, he was attempting to swim ashore', 'Diving into water', 'Fishing trawler Flavio Gioia ', 'Swimming in canal', 'Swimming after harpooned whale capsized boat', 'Removing shark from a trap', 'Spearfishing, but swimming on surface', 'Surfing & dangling foot in water amid baitfish', 'Wreck of the USS Somers', 'Thrown into water from fishing dinghy', 'Board sailing', 'Helping angler land a shark', 'Standing on sandbar', 'Paddleskiing', 'Five men on makeshift raft after their 10 m fishing boat  capsized and sank in rough seas. Survivors rescued after  7.5 hours in the water', "Fishing, standing in 2' of water", 'ship torpedoed 400 miles off the African coas. Man was clinging to hatch cover', 'Commercial diver (submerged or treading water)', 'Attempting to drag hooked shark ashore by its tail', 'Cargo ship Dara sank after collision with another ship during a severe storm', 'Surf bathing', 'The steamships Thingvalla and Geiser collided', 'Diving on a wreck', 'On expedition filming a feature movie & standing on tripod', 'Spearfishing, but walking carrying fish on end of speargun', 'Kneeling in the water', "On board 51' fishing vessel One Ki", 'Jumped off surfboard & landed on the shark', 'Oyster fishing', 'Paddle boarding', 'Jerked overboard while pole fishing for tuna', 'Wading, when he stepped on the shark', 'Jumped into river', 'Boat Miss Becky  sank 12 miles from shore', 'Free diving for abalone (surfacing)', 'Bathing alongside ship', 'Wreck of the Union Steamship Company 982-ton iron steamer Kafir', 'M.V. Tropical sank. Sole survivor rode oil drums for 8 days without food or water.', 'Returning to shore, collided with shark', 'Attempting to rescue woman seized by shark', 'Free diving & spearfishing', 'Spearfishing, shot a sandtiger shark. Cord to spear tangled round his legs & a wave washed him onto a reef.', 'Fishing, holding fish in right hand', 'Dress diving', 'Attaching a line at sea', 'Sight-seeing', 'Swimming with pod of dolphins', "40' fishing boat sank", 'Fishing for bluefish, shark leapt into dory', 'He was fighting a shark when his boat capsized & he disappeared', 'Lying atop surfboard', 'Washing', 'Boat capsized', 'Measuring sharks', 'Diving, gathering shellfish', 'Scuba diving (ascending using scooter)', 'Surfing, paddling s

In [ ]:
"""

Let's determine some bins for classifying the data.
We will base this on the following sources:

https://en.wikipedia.org/wiki/List_of_water_sports

https://www.themost10.com/popular-water-sports/

- Fishing
- Spearfishing
- Diving / Scuba Diving / Snorkeling / Freediving
- Feeding
- Surfing
- Swiming
- Parasailing
- Kitesurfing / Kiteboarding
- Deep sea fishing / Big game fishing
- Kayaking/ Canoeing
- Jet Skiing / Water Skiing
- Rafting
- Wakeboarding / Wakesurfing
- Yachting

...and finally...

- Shark feeding

"""

In [ ]:
#s1 = pd.Series(['a', 'b', 'a', 'c', 'a', 'b'])
#s2 = pd.Series(['a', 'f', 'a', 'd', 'a', 'f', 'f'])
#d = pd.DataFrame({'s1': s1, 's2': s2})
#d.apply(pd.value_counts).plot(kind='bar', subplots=True)