# Importing relevant libraries

In [130]:
import pandas as pd
import numpy as np
import re

# Importing data

In [131]:
shark_attacks = pd.read_csv('C:/Users/pfaprado/Documents/IronHack/2021-01-22-project-shark-attack/attacks.csv', encoding='latin1')

# Preliminary analysis of data

In [132]:
shark_attacks.size

# We have about 617352 elementos na tabela.

617352

In [133]:
shark_attacks.shape

# We have 24723 entries of 24 types of data.

(25723, 24)

In [134]:
shark_attacks.info()

# Too many data entries without many infos such as Age, Time, Sex, Fatal, etc. Last columns can't be used.
# Year is a float64, should have been an integer.
# Age should have been specified as integer.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [135]:
# Specifically, about the types of data columns.

shark_attacks.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

In [136]:
# Let's show all the columns available through a max_columns and a head method.

pd.options.display.max_columns = None
shark_attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [137]:
# All the columns availables.

shark_attacks.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [138]:
# Let's count all the occurrences present in the column Fatal.

shark_attacks['Fatal (Y/N)'].value_counts()

# Highest portion of shark attacks are non-fatal.

N          4293
Y          1388
UNKNOWN      71
 N            7
M             1
y             1
2017          1
N             1
Name: Fatal (Y/N), dtype: int64

In [139]:
shark_attacks['Activity'].value_counts()

# Highest portion occurred during surfing, swimming or fishing.
# !However there are way too many categories to affirm anything at this point!

Surfing                                                                                                                    971
Swimming                                                                                                                   869
Fishing                                                                                                                    431
Spearfishing                                                                                                               333
Bathing                                                                                                                    162
                                                                                                                          ...
Attempting to drive shark away from sailing regatta                                                                          1
The Ward liner Esperanza stranded during a gale & she leapt overboard to rescue her dog which had been swept overboard.      1
Wreck of a sampam                                                                                                            1
Light aircraft ditched at sea                                                                                                1
Sinking of the ferryboat Don Juan                                                                                            1
Name: Activity, Length: 1532, dtype: int64

# Jaws Adventures: marketing shark feeding

In [140]:
"""
Our company, "Jaws Adventures", offers scuba diving and free diving for people.
We would like to analyse and market a new product: shark feeding.
However people may express distress to the idea of feeding sharks and the risks involved.
Let's analyse whether feeding sharks is safer than other activities already offered by our company.
"""

"""
For this, we will need to pull the data from columns:
- Activity (categorical)
- Fatal (Y/N) (categorical, binary: Y/N)
This data will represent all kinds of attacks registered.

However, we know that the database is kind of sketchy, so we will need to do some data wrangling (cleaning) before.
"""

fatality_activity = shark_attacks[['Activity','Fatal (Y/N)']]

fatality_activity

          Activity Fatal (Y/N)
0         Paddling           N
1         Standing           N
2          Surfing           N
3          Surfing           N
4      Free diving           N
...            ...         ...
25718          NaN         NaN
25719          NaN         NaN
25720          NaN         NaN
25721          NaN         NaN
25722          NaN         NaN

[25723 rows x 2 columns]

In [141]:
# Let's check how many nulls we have in our dataset in each column.

null_cols = shark_attacks.isnull().sum()

null_cols

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

In [142]:
# Let's understand the cases where the entries are null for Activity.

null_display = shark_attacks[shark_attacks['Activity'].isnull() == True]
null_display

# There is no apparent reason or correlation between null entries of Activity to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
47,2018.01.28,28-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,male,M,18,Injuries to right leg,N,08h00,Bull shark,"ABC.net.au, 01/28/2018",2018.01.28-ConeBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.28,2018.01.28,6256.0,NaN,NaN
108,2017.07.29.a,29-Jul-2017,2017.0,Unprovoked,USA,South Carolina,"DeBordieu Colony, Georgetown County",NaN,female x 2,F,12,Bite to left thigh / minor injury,N,Afternoon,NaN,"C. Creswell, GSAF",2017.07.29.a-Georgetown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.a,2017.07.29.a,6195.0,NaN,NaN
112,2017.07.23.b,23-Jul-2017,2017.0,Unprovoked,USA,New Jersey,Ventnor,NaN,Isabella Smith,F,NaN,Minor injury to hand,N,NaN,Sandtiger shark 2',A. Smith,2017.07.23.b-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.23.b,2017.07.23.b,6191.0,NaN,NaN
114,2017.07.22,22-Jul-2017,2017.0,Unprovoked,USA,Florida,"Snipes Point, Monroe County",NaN,female,F,40,Foot bitten,N,12h30,"""A small shark""","NBC Miami, 7/23/2017",2017.07.22-Keys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.22,2017.07.22,6189.0,NaN,NaN
154,2017.04.17.b,17-Apr-2017,2017.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,NaN,NaN,NaN,Minor bite to the foot,N,Afternoon,NaN,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
# Let's understand the cases where the entries are null for Fatal.

null_display2 = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display2

# There is no apparent reason or correlation between null entries of Fatal to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,CastellÃ³n,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
# We previously noticed that year and age were float and object, respectively.
# Let's make them both integer.

# shark_attacks['Year'] = shark_attacks['Year'].astype('int')

# shark_attacks['Year'].dtype

In [145]:
# Let's check for duplicates in our database and remove them:

before = len(shark_attacks)
shark_attacks = shark_attacks.drop_duplicates()
after = len(shark_attacks)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  19411

In [158]:
# That's how our database is now:

shark_attacks

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Test1
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Test1
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Test1
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,Test1
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,Test1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0,NaN,NaN,Test1
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0,NaN,NaN,Test1
6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test1
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test1
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test1

## Data Cleaning: 'Fatal (Y/N)'

In [147]:
# Let's check the unique values of the column Fatal (Y/N) and its incidence in our database.

print(f"""
These are the occurrences of the values for Fatal (Y/N):
{shark_attacks['Fatal (Y/N)'].value_counts()}
""")

print(f"""
These are the unique values of the Fatal (Y/N) column:
{set(shark_attacks['Fatal (Y/N)'])}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.
""")

These are the occurrences of the values for Fatal (Y/N):
N          4293
Y          1388
UNKNOWN      71
 N            7
M             1
N             1
y             1
2017          1
Name: Fatal (Y/N), dtype: int64


These are the unique values of the Fatal (Y/N) column:
{nan, '2017', 'Y', 'UNKNOWN', ' N', 'y', 'N', 'M', 'N '}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.

### Checking uniques.

In [148]:
#Let's examine the case of 2017. There is only one entry classified as 2017.

case_2017_list = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == '2017']

case_2017_list

# As there is no information regarding the survivability on other columns,
# we will dismiss this entry in the dropping section.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
786,2012.06.10,10-Jun-2012,2012.0,Provoked,ITALY,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,57,Lower left leg injured PROVOKED ACCIDENT,2017,Morning,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0,NaN,NaN

In [149]:
# Let's examine the case of UNKNOWN. There are many entries classified as UNKNOWN.

case_UNKNOWN = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == 'UNKNOWN']
print(case_UNKNOWN)

# Printaremos tambÃ©m os Ã­ndices referentes Ã  entrada UNKNOWN. Futuramente retiraremos as linhas com base nessa lista.

case_UNKNOWN_list = list(case_UNKNOWN.index)
print(case_UNKNOWN_list)

# Examining the set of unique values of injury, we don't have any other relevant info on the fatality of the entries.
# So we can't take any action to classify these entries neither as Y nor as N.

set(case_UNKNOWN['Injury'])

# We better take these data out of the database.

       Case Number           Date    Year        Type    Country  \
624     2013.09.08    08-Sep-2013  2013.0  Unprovoked        USA
1270  2008.04.20.a    20-Apr-2008  2008.0  Unprovoked  AUSTRALIA
2250    1997.06.07    07-Jun-1997  1997.0  Unprovoked     BRAZIL
2260    1997.02.21    21-Feb-1997  1997.0  Unprovoked        USA
2267    1996.12.29    29-Dec-1996  1996.0  Unprovoked  AUSTRALIA
...            ...            ...     ...         ...        ...
6167  1617.00.00.R  Reported 1617  1617.0  Unprovoked      INDIA
6169    1595.00.00           1595  1595.0  Unprovoked      INDIA
6171    1555.00.00           1555  1555.0  Unprovoked        NaN
6172    1554.00.00       Ca. 1554  1554.0  Unprovoked     FRANCE
6277       ND.0025    Before 1927     0.0  Unprovoked  AUSTRALIA

                   Area                            Location  \
624      South Carolina  St. Helena Island, Beaufort County
1270    New South Wales                       Crescent Head
2250     Rio de Janeiro          Copacabana, Rio de Janeiro
2260             Hawaii                 Sunset Beach, O'ahu
2267         Queensland                        Coolum Beach
...                 ...                                 ...
6167        West Bengal                        Ganges Delta
6169             Kerala                        River Cochin
6171                NaN                                 NaN
6172  Nice & Marseilles                                 NaN
6277    New South Wales      Spectacle Island, Port Jackson

                                               Activity  \
624                                                 NaN
1270                                                NaN
2250                                            Bathing
2260                                                NaN
2267                                            Surfing
...                                                 ...
6167                                                NaN
6169  Ship lay at anchor & man was working on its ru...
6171                                           Swimming
6172                                                NaN
6277                                                NaN

                               Name Sex   Age  \
624                          female    F  NaN
1270                Jamie Adlington    M  NaN
2250              JosÃ© Luiz Lipiani    M  NaN
2260                Gersome Perreno    M  NaN
2267                     Blair Hall    M   18
...                             ...  ...  ...
6167                  Indian people  NaN  NaN
6169                           male    M  NaN
6171                           male    M  NaN
6172          males (wearing armor)    M  NaN
6277  male, the Sergeant of Marines    M  NaN

                                                 Injury Fatal (Y/N)   Time  \
624                                          No details     UNKNOWN    NaN
1270                                                NaN     UNKNOWN    NaN
2250                                                NaN     UNKNOWN    NaN
2260                                         No details     UNKNOWN    NaN
2267                                                NaN     UNKNOWN  18h00
...                                                 ...         ...    ...
6167                                                NaN     UNKNOWN    NaN
6169  Leg severed mid-thigh, hand severed, arm above...     UNKNOWN    NaN
6171                                                NaN     UNKNOWN    NaN
6172                                                NaN     UNKNOWN    NaN
6277                                                NaN     UNKNOWN    NaN

                   Species                      Investigator or Source  \
624                     NaN                           WIS-TV, 9/9/2013
1270     Tiger shark, 2.3m                              T. Peake, GSAF
2250                    NaN                            Globo, 6/9/1997
2260                    NaN                                  G. Balazs
2267                    NaN            The Advertiser, 12/30/1996, p.3
...                     ...                                        ...
6167                    NaN    H. Edwards, p.31, citing Samuel Purchas
6169                    NaN  The Voyage of John Huyghen van Linschoten
6171                    NaN                               Olaus Magnus
6172  Possibly white sharks                               G. Rondelet
6277                    NaN                                  H. Capper

                                  pdf  \
624          2013.09.08-St-Helena.pdf
1270       2008.04.20.a-Adlington.pdf
2250        1997.06.07-NV-Lipiani.pdf
2260        1997.02.21-NV-Perreno.pdf
2267         1996.12.29-BlairHall.pdf
...                               ...
6167           1617.00.00-Purchas.pdf
6169            1595.00.00-Cochin.pdf
6171    1555.00.00 - Olaus Magnus.pdf
6172          1554.00.00-Rondelet.pdf
6277  ND-0025-Sgt-SpectacleIsland.pdf

                                           href formula  \
624   http://sharkattackfile.net/spreadsheets/pdf_di...
1270  http://sharkattackfile.net/spreadsheets/pdf_di...
2250  http://sharkattackfile.net/spreadsheets/pdf_di...
2260  http://sharkattackfile.net/spreadsheets/pdf_di...
2267  http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                 ...
6167  http://sharkattackfile.net/spreadsheets/pdf_di...
6169  http://sharkattackfile.net/spreadsheets/pdf_di...
6171  http://sharkattackfile.net/spreadsheets/pdf_di...
6172  http://sharkattackfile.net/spreadsheets/pdf_di...
6277  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number.1  \
624   http://sharkattackfile.net/spreadsheets/pdf_di...    2013.09.08
1270  http://sharkattackfile.net/spreadsheets/pdf_di...  2008.04.20.a
2250  http://sharkattackfile.net/spreadsheets/pdf_di...    1997.06.07
2260  http://sharkattackfile.net/spreadsheets/pdf_di...    1997.02.21
2267  http://sharkattackfile.net/spreadsheets/pdf_di...    1996.12.29
...                                                 ...           ...
6167  http://sharkattackfile.net/spreadsheets/pdf_di...  1617.00.00.R
6169  http://sharkattackfile.net/spreadsheets/pdf_di...    1595.00.00
6171  http://sharkattackfile.net/spreadsheets/pdf_di...    1555.00.00
6172  http://sharkattackfile.net/spreadsheets/pdf_di...    1554.00.00
6277  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0025

     Case Number.2  original order Unnamed: 22 Unnamed: 23
624     2013.09.08          5679.0         NaN         NaN
1270  2008.04.20.a          5033.0         NaN         NaN
2250    1997.06.07          4053.0         NaN         NaN
2260    1997.02.21          4043.0         NaN         NaN
2267    1996.12.29          4036.0         NaN         NaN
...            ...             ...         ...         ...
6167  1617.00.00.R           136.0         NaN         NaN
6169    1595.00.00           134.0         NaN         NaN
6171    1555.00.00           132.0         NaN         NaN
6172    1554.00.00           131.0         NaN         NaN
6277       ND.0025            26.0         NaN         NaN

[71 rows x 24 columns]
[624, 1270, 2250, 2260, 2267, 2295, 2307, 2323, 2328, 2388, 2404, 2409, 2648, 2650, 2661, 2806, 2882, 2900, 2943, 2996, 2998, 3006, 3038, 3041, 3298, 3396, 3411, 3429, 3434, 3507, 3545, 3552, 3712, 3774, 3794, 3838, 3841, 4060, 4208, 4256, 4269, 4310, 4323, 4517, 4689, 4786, 4787, 4976, 4998, 5029, 5159, 5270, 5347, 5409, 5555, 5615, 5653, 5656, 5674, 5708, 5709, 5998, 6081, 6153, 6165, 6166, 6167, 6169, 6171, 6172, 6277]

{'"Painfully injured" but no details',
 'Calf removed, not known if he survived ',
 'Details unknown, possibly a PROVOKED INCIDENT',
 'Involved a speared shark but no other details PROVOKED INCIDENT',
 'Leg severed mid-thigh, hand severed, arm above elbow and part of buttocks. Not known if he survived',
 'Man landed at Cape LevÃªque lighthouse in critical condition after being bitten by a shark. Not known if he survived.',
 'No details',
 'No details, "recovering in Darwin Hospital"',
 'No details, it was the year the first settlers came ashore in Holdfast Bay, Port Pirie',
 'No details, listed as PROVOKED INCIDENT',
 'No injury',
 'Severe bite to thigh. Not known if he survived',
 'Shark involvement not confirmed',
 'Unprovoked, but circumstances unknown',
 nan}

In [150]:
# Let's examine the case of M. There is only one entry classified as M.

case_M = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == 'M']
print(case_M)

# Printaremos tambÃ©m os Ã­ndices referentes Ã  entrada M. Futuramente retiraremos as linhas com base nessa lista.

case_M_list = list(case_M.index)
print(case_M_list)

# It seems it was only a laceration and the input was supposed to be N, not M. We will change it to N.

      Case Number         Date    Year      Type           Country      Area  \
285  2016.04.18.b  18-Apr-2016  2016.0  Provoked  FRENCH POLYNESIA  Tuamotos

         Location      Activity         Name Sex  Age  \
285  Makemo Atoll  Spearfishing  Hoata Iotua    M  22

                                                Injury Fatal (Y/N)     Time  \
285  Laceration to knee by speared shark PROVOKED I...           M  Morning

                 Species  Investigator or Source                     pdf  \
285  Grey reef shark, 2 m   TNTV News, 4/19/2016  2016.04.18.b-Iotua.pdf

                                          href formula  \
285  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                  href Case Number.1  \
285  http://sharkattackfile.net/spreadsheets/pdf_di...  2016.04.18.b

    Case Number.2  original order Unnamed: 22 Unnamed: 23
285  2016.04.18.b          6018.0         NaN         NaN
[285]

In [ ]:
re.findall('end')

In [157]:
# Let's examine the case of NaN. There are many entries like this.
# We will reclassify the values of NaN based on columns 'Injury' and 'Species' since it seems the data entrier
# had put some keywords such as FATAL and Death on these columns and could lead us to improve our dataset.

# Let's define a function to apply to our dataset, where we classify the values in Fatal_adjusted based on
# columns 'Injury' and 'Species', when they do have the info 'death' or 'fatal'.

shark_attacks['Fatal_adjusted'] = 'Test1'
print(shark_attacks['Fatal_adjusted'])

fatal_list = re.findall('[fF][aA][tT][aA][lL]', shark_attacks['Injury'])
print(fatal_list)

def classifier(x):
    
    fatal_list = re.findall('[fF][aA][tT][aA][lL]', x)
    if fatal_list in shark_attacks['Injury'] or shark_attacks['Species']:
        return 'Y'
    
    elif re.findall('[dD][eE][aA][tT][hH]', x) in shark_attacks['Injury'] or shark_attacks['Species']:
        return 'Y'
    
    else:
       pass


# Let's create another column to adjust the data from 'Fatal (Y/N)', called 'Fatal_adjusted'.
    
shark_attacks['Fatal_adjusted'] = shark_attacks['Injury'].apply(classifier)

print(shark_attacks['Fatal_adjusted'])

0        Test1
1        Test1
2        Test1
3        Test1
4        Test1
         ...
6307     Test1
6308     Test1
6309     Test1
8702     Test1
25722    Test1
Name: Fatal_adjusted, Length: 6312, dtype: object

TypeError: expected string or bytes-like object

### Row dropping

In [116]:
# Let's drop the case of 2017 (row 786).
case_2017_list = [786]

# Let's drop the case of UNKNOWNs ().
    # case_UNKNOWN_list
    
shark_attacks_v1 = shark_attacks.drop(case_UNKNOWN_list)
shark_attacks_v2 = shark_attacks_v1.drop(case_2017_list)

### Row adjusting

In [74]:
# For M, we will update the row 285 for Fatal (Y/N) from M to N.

shark_attacks_v2.loc[285,'Fatal (Y/N)'] = 'N'

# Checking the value update:

print(shark_attacks_v2.loc[285,'Fatal (Y/N)'])

N

### Transform the dataframe series into a list.

In [75]:
# 1.Transform the dataframe series into a list.

fatal_list = list(shark_attacks_v2['Fatal (Y/N)'])

#shark_attacks['Fatal (Y/N)'] = shark_attacks[shark_attacks['Fatal (Y/N)'] == 'N ' | ]

### Upper case the strings.

In [ ]:
# 2. Upper case the strings.

# Since we have a list of strings, we can only upper case them once we treat each one exclusively,
# given that upper() is a method of strings. We can, however, create a list comprehension to treat
# every string individually like is done in a loop.

fatal_list = [ element.upper() for element in fatal_list]

fatal_list

In [ ]:
# There are some values for N that have spaces after or before them. We cant strip these spaces in the entries.

In [ ]:
# Let's check the unique values of the column Activity.

print(set(shark_attacks['Activity']))

# It's definetely chaotic and somewhat anedoctal (too many descriptions).
# We will have to categorize them better, maybe through bins.

In [ ]:
"""

Let's determine some bins for classifying the data.
We will base this on the following sources:

https://en.wikipedia.org/wiki/List_of_water_sports
https://www.themost10.com/popular-water-sports/

- Fishing: Fishing / Spearfishing / Deep sea fishing / Big game fishing
- Diving: Diving / Scuba Diving / Snorkeling / Freediving
- Surfing
- Swiming
- Parasailing
- Kayaking/ Canoeing / Rafting
- Jet Skiing / Water Skiing
- Wakeboarding / Wakesurfing
- Kitesurfing / Kiteboarding
- Yachting
- Other activities

...and finally...

- Shark feeding

"""

## Data Cleaning: 'Activity'

## Data Cleaning: 'Type'

In [25]:
print(shark_attacks['Type'].value_counts())

# We will have to reclassify this column too, based on text of other columns.

Unprovoked      4595
Provoked         574
Invalid          547
Sea Disaster     239
Boating          203
Boat             137
Questionable       2
Boatomg            1
Name: Type, dtype: int64

In [32]:
shark_attacks[shark_attacks['Type'] == 'Invalid']

# Analyzing the column when Invalid was input as Type,

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0,NaN,NaN
31,2018.04.10.R,Reported 10-Apr-2018,2018.0,Invalid,BRAZIL,Alagoas,"Praia de SauaÃ§uhy, MaceiÃ³",Fishing,Josias Paz,M,56,Injury to ankle from marine animal trapped in ...,N,NaN,Shark involvement not confirmed,"K. McMurray, TrackingSharks.com",2018.04.10.R-Paz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.10.R,2018.04.10.R,6272.0,NaN,NaN
43,2018.02.14,14-Feb-2018,2018.0,Invalid,AUSTRALIA,Queensland,Mooloolaba Beach,Swimming,Sharna Babd,F,NaN,"Collision / No injury, no attack",N,18h00,Possibly a wobbegong,"Sunshine Coast Daily, 2/15/2018",2018.02.14-Babd.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.14,2018.02.14,6260.0,NaN,NaN
44,2018.02.11,11-Feb-2018,2018.0,Invalid,BRAZIL,"Boi Island, Victoria",Espirito Santo,Cleaning fish,Rosalida Souza,F,46,Lacerations to 4 toes of right foot,N,NaN,"Injury believed caused by an eel, not a shark",TrackingSharks.com,2018.02.11-Rosilda.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.11,2018.02.11,6259.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,CÃ´te d'Azur,St. Tropez,Bathing,Samuel Matthews,M,NaN,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00,156.0,NaN,NaN
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00,146.0,NaN,NaN
6164,1642.00.00.b,Late 1600s Reported 1728,1642.0,Invalid,GUINEA,NaN,NaN,Went overboard,crew member of the Nieuwstadt,M,NaN,FATAL,NaN,NaN,Questionable,"History of the Pyrates, by D. Defoe, Vol. 2, p.28",1642.00.00.b-Nieuwstadt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1642.00.00.b,1642.00.00.b,139.0,NaN,NaN
6227,ND.0086,"No date, Before 1975",0.0,Invalid,PAPUA NEW GUINEA,Milne Bay Province,"D'Entrecasteaux islands, 20 miles off the coast",Scuba diving,Dan Hogan,M,NaN,Said to be fatal and involve a 4.6 m to 6 m [1...,Y,NaN,Questionable,"F. Dennis, pp.15-16",ND-0086-DanHogan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0086,ND.0086,76.0,NaN,NaN
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081,71.0,NaN,NaN

## Plotting

In [24]:
#s1 = pd.Series(['a', 'b', 'a', 'c', 'a', 'b'])
#s2 = pd.Series(['a', 'f', 'a', 'd', 'a', 'f', 'f'])
#d = pd.DataFrame({'s1': s1, 's2': s2})
#d.apply(pd.value_counts).plot(kind='bar', subplots=True)